# -*- coding: utf-8 -*-
"""Linh test 16

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rCJHlzQ6Wn_51X78qSSDl36J6RLRqIR
"""

# --- BƯỚC 0: IMPORT CÁC THƯ VIỆN CẦN THIẾT ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from IPython.display import display # Để hiển thị DataFrame đẹp hơn

# Thư viện Preprocessing
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

# Thư viện Mô hình Clustering
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture

# Thư viện Đánh giá
from sklearn.metrics import silhouette_score, davies_bouldin_score

# Thư viện Hồi quy
import statsmodels.api as sm
import warnings

# Cài đặt hiển thị
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)
warnings.filterwarnings('ignore')
print("-- [BƯỚC 0] Tất cả thư viện đã được nhập thành công. --")


# --- BƯỚC 1: TẢI VÀ KỸ THUẬT ĐẶC TRƯNG (FEATURE ENGINEERING) ---

print("\n-- [BƯỚC 1] Đang tải dữ liệu và xây dựng đặc trưng... --")
try:
    # Tải TẤT CẢ 4 tệp cần thiết ngay từ đầu
    df_trans = pd.read_csv('transaction_data.csv')
    df_cust = pd.read_csv('customer_profile.csv')
    df_prod = pd.read_csv('product_master.csv')
    df_macro = pd.read_csv('macro_context.csv')

    # Chuyển đổi kiểu dữ liệu ngày tháng
    df_trans['Date_Time'] = pd.to_datetime(df_trans['Date_Time'])
    df_macro['Date'] = pd.to_datetime(df_macro['Date']).dt.date.astype(str)
    print("Tải 4 tệp dữ liệu thành công.")
except FileNotFoundError:
    print("LỖI: Không tìm thấy 1 trong 4 tệp CSV. Vui lòng đảm bảo 4 tệp (trans, cust, prod, macro) nằm trong cùng thư mục.")
    # exit()

# 1.1. Xây dựng đặc trưng RFM
print("Đang xây dựng đặc trưng RFM...")
snapshot_date = df_trans['Date_Time'].max() + pd.Timedelta(days=1)

rfm_df = df_trans.groupby('Customer_ID').agg(
    Recency=('Date_Time', lambda x: (snapshot_date - x.max()).days),
    Frequency=('Transaction_ID', 'nunique'),
    Monetary=('Total_Paid', 'sum')
).reset_index()

# 1.2. Kết hợp và Xây dựng đặc trưng Hồ sơ (Profile)
print("Đang kết hợp dữ liệu và tạo đặc trưng 'Age'...")
df_analysis = pd.merge(df_cust, rfm_df, on='Customer_ID', how='left')

# Xử lý khách hàng không có giao dịch (nếu có)
df_analysis['Recency'] = df_analysis['Recency'].fillna(999) # Giả định R=999 cho KH không có giao dịch
df_analysis[['Frequency', 'Monetary']] = df_analysis[['Frequency', 'Monetary']].fillna(0)

# Tạo đặc trưng 'Age'
current_year = snapshot_date.year
df_analysis['Age'] = current_year - df_analysis['YoB']

# Xử lý ngoại lệ (Outliers) cho RFM - Sử dụng Capping ở Phân vị 99%
print("Đang xử lý ngoại lệ cho RFM (capping ở Q99)...")
for col in ['Recency', 'Frequency', 'Monetary']:
    cap_value = df_analysis[col].quantile(0.99)
    df_analysis[col] = df_analysis[col].clip(upper=cap_value)

# 1.3. Chọn các đặc trưng cuối cùng cho mô hình
features_to_cluster = [
    'Age', 'Recency', 'Frequency', 'Monetary',  # Số
    'Income level', 'Membership_Tier',          # Xếp hạng
    'Occupation', 'Gender'                      # Danh nghĩa
]
df_model_input = df_analysis[features_to_cluster].copy()
print(f"Hoàn tất BƯỚC 1. Dữ liệu đầu vào có {df_model_input.shape[0]} khách hàng và {df_model_input.shape[1]} đặc trưng.")


# --- BƯỚC 2: TIỀN XỬ LÝ (PREPROCESSING PIPELINE) ---

print("\n-- [BƯỚC 2] Xây dựng Pipeline Mã hóa & Chuẩn hóa... --")

# 2.1. Định nghĩa các nhóm cột
numerical_features = ['Age', 'Recency', 'Frequency', 'Monetary']
income_levels = ['< 2M', '2-5M', '5-10M', '10-20M', '20-50M', '> 50M']
membership_tiers = ['Standard', 'Silver', 'Gold', 'Diamond']
ordinal_features = ['Income level', 'Membership_Tier']
nominal_features = ['Occupation', 'Gender']

# 2.2. Xây dựng các đường ống (pipeline) con
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
ordinal_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder(categories=[income_levels, membership_tiers], handle_unknown='use_encoded_value', unknown_value=-1))
])
nominal_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

# 2.3. Kết hợp các pipeline con bằng ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_features),
        ('ord', ordinal_transformer, ordinal_features),
        ('nom', nominal_transformer, nominal_features)
    ],
    remainder='passthrough'
)

# 2.4. Áp dụng preprocessor
X_scaled = preprocessor.fit_transform(df_model_input)
print("Pipeline tiền xử lý hoàn tất.")

# --- BƯỚC 3: XÁC ĐỊNH SỐ CỤM TỐI ƯU (K) ---

print("\n-- [BƯỚC 3] Đang xác định K tối ưu (Elbow & Silhouette)... --")
inertia_values = []
silhouette_scores = []
K_range = range(2, 9) # Kiểm tra từ 2 đến 8 cụm

print("Đang chạy K-Means với các K khác nhau...")
for k in K_range:
    kmeans_test = KMeans(n_clusters=k, init='k-means++', random_state=42, n_init=10)
    kmeans_test.fit(X_scaled)
    inertia_values.append(kmeans_test.inertia_)
    score = silhouette_score(X_scaled, kmeans_test.labels_)
    silhouette_scores.append(score)

print("Hoàn tất tính toán WCSS (Inertia) và Silhouette.")

# 3.1. Vẽ biểu đồ Elbow
plt.figure(figsize=(18, 6))
plt.subplot(1, 2, 1)
plt.plot(K_range, inertia_values, 'bo-'); plt.xlabel('Số cụm (K)'); plt.ylabel('WCSS (Inertia)'); plt.title('Phương pháp Elbow (Elbow Method)'); plt.grid(True)
# 3.2. Vẽ biểu đồ Silhouette
plt.subplot(1, 2, 2)
plt.plot(K_range, silhouette_scores, 'rs-'); plt.xlabel('Số cụm (K)'); plt.ylabel('Silhouette Score'); plt.title('Chỉ số Silhouette'); plt.grid(True)
plt.tight_layout()
plt.show()

# --- BƯỚC 4: HUẤN LUYỆN VÀ ĐÁNH GIÁ MÔ HÌNH K-MEANS ---

print("\n-- [BƯỚC 4] Huấn luyện & Đánh giá mô hình K-Means Clustering... --")
# Chọn K=3 dựa trên biểu đồ
N_CLUSTERS = 3

model_name = "K-Means"
model = KMeans(n_clusters=N_CLUSTERS, init='k-means++', random_state=42, n_init=10)
print(f"\nĐang huấn luyện mô hình {model_name}...")
labels = model.fit_predict(X_scaled)
labels_dict = {model_name: labels} # Lưu nhãn

silhouette = silhouette_score(X_scaled, labels)
davies_bouldin = davies_bouldin_score(X_scaled, labels)
print(f" - {model_name}: Silhouette Score = {silhouette:.4f}, Davies-Bouldin Index = {davies_bouldin:.4f}")
print("Hoàn tất BƯỚC 4.")


# --- BƯỚC 5: GIẢM CHIỀU DỮ LIỆU BẰNG PCA & TRỰC QUAN HÓA CỤM K-MEANS ---

print("\n-- [BƯỚC 5] Đang giảm chiều dữ liệu bằng PCA và Trực quan hóa K-Means... --")
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled)
df_pca = pd.DataFrame(data=X_pca, columns=['PC1', 'PC2'])
df_pca[model_name] = labels_dict[model_name]

# Vẽ biểu đồ PCA
plt.figure(figsize=(8, 6))
sns.scatterplot(x='PC1', y='PC2', hue=model_name, data=df_pca, palette='viridis', legend='full', alpha=0.7)
plt.title(f'{model_name} Clustering (PCA)')
plt.grid(True)
plt.tight_layout()
plt.show()
print("Hoàn tất BƯỚC 5.")

# --- BƯỚC 6: PHÂN TÍCH HỒ SƠ KHÁCH HÀNG THEO CỤM ---

print("\n-- [BƯỚC 6] Đang phân tích hồ sơ khách hàng theo cụm... --")
df_analysis['Cluster'] = labels_dict["K-Means"]

print("\n--- Hồ sơ cụm (đặc trưng số trung bình) ---")
cluster_profiles_num = df_analysis.groupby('Cluster')[numerical_features + ['Age']].mean()
display(cluster_profiles_num)

print("\n--- Hồ sơ cụm (đặc trưng phân loại phổ biến nhất) ---")
for col in ordinal_features + nominal_features:
    print(f"\nĐặc trưng: {col}")
    try:
        display(df_analysis.groupby('Cluster')[col].agg(lambda x: x.mode()[0] if not x.mode().empty else 'N/A').to_frame(name=f'Most_Frequent_{col}'))
    except IndexError:
        print(f"Không thể tính mode cho cột {col}")
print("Hoàn tất BƯỚC 6.")

print("\n--- [GIAI ĐOẠN 1] HOÀN TẤT. ---")
print("Các biến df_trans, df_cust, df_prod, df_macro, và df_analysis (đã có Cluster) đã sẵn sàng.")

# --- [GIAI ĐOẠN 2] TÍNH TOÁN ĐỘ CO GIÃN (PED) ---

# ##################################################################
# --- BƯỚC 7 (Mô hình 5): TÍNH PED (LOGIC ĐÚNG) ---
# Logic mới: log(Q_Category) ~ log(Price_Index_Category) + Controls
# ##################################################################

print("\n\n--- [BƯỚC 7 - Mô hình 5] Đang tính PED (Mô hình Category + Price Index)... ---")

# 7.1. Chuẩn bị dữ liệu (df_trans, df_prod, df_analysis đã có trong bộ nhớ)
print("Đang chuẩn bị dữ liệu...")
try:
    # Merge trans + prod (để lấy Category)
    df_trans_with_cat = pd.merge(df_trans, df_prod[['Product_ID', 'Category']], on='Product_ID', how='left')

    # Merge (trans + prod) + analysis (để lấy Cluster)
    df_full_segmented = pd.merge(
        df_trans_with_cat,
        df_analysis[['Customer_ID', 'Cluster']],
        on='Customer_ID',
        how='left'
    )

    df_full_segmented = df_full_segmented.dropna(subset=['Cluster', 'Category'])
    df_full_segmented = df_full_segmented[df_full_segmented['Quantity'] > 0]
except NameError:
    print("LỖI: Một trong các DataFrame (df_trans, df_prod, df_analysis) không tồn tại. Vui lòng chạy file '1_Segmentation.py' trước.")
    # exit()

# Đảm bảo cột 'Date' tồn tại
df_full_segmented['Date'] = pd.to_datetime(df_full_segmented['Date_Time']).dt.date.astype(str)

# [LOGIC MỚI] Tạo cột Total_List_Price (Tổng giá niêm yết)
df_full_segmented['Total_List_Price'] = df_full_segmented['Quantity'] * df_full_segmented['Unit_Price_Listed']

# 7.2. Tổng hợp theo Date, Cluster, VÀ CATEGORY
print("Đang tổng hợp dữ liệu (Lấy TỔNG Q, TỔNG Paid, TỔNG List) theo Category...")
df_agg_cat = df_full_segmented.groupby(['Date', 'Cluster', 'Category']).agg(
    Total_Quantity=('Quantity', 'sum'),
    Total_Paid_Agg=('Total_Paid', 'sum'),
    Total_List_Price_Agg=('Total_List_Price', 'sum') # [LOGIC MỚI]
).reset_index()

# 7.3. [LOGIC MỚI] Tạo biến "Price_Index" (cho từng Category)
df_agg_cat = df_agg_cat[df_agg_cat['Total_List_Price_Agg'] > 0]
df_agg_cat['Price_Index'] = df_agg_cat['Total_Paid_Agg'] / df_agg_cat['Total_List_Price_Agg']
df_agg_cat = df_agg_cat[df_agg_cat['Price_Index'] > 0]
print("Đã tạo 'Price_Index' (Total_Paid / Total_List_Price) cho từng Category.")

# 7.4. Merge với df_macro để lấy biến kiểm soát
# (df_macro đã được tải ở BƯỚC 1 và 'Date' đã là string)
try:
    df_agg_cat['Date'] = df_agg_cat['Date'].astype(str) # Đảm bảo kiểu string

    df_agg_cat_macro = pd.merge(
        df_agg_cat,
        df_macro[['Date', 'Promotion_Campaign', 'Is_Weekend', 'Is_Holiday', 'Monthly_Index']],
        on='Date',
        how='left'
    )
    print("Đã thêm các biến kiểm soát (Promotion, Weekend, Holiday, Monthly_Index).")

except Exception as e:
    print(f"LỖI NGHIÊM TRỌNG KHI MERGE: {e}")
    # exit()

# 7.5. Phân tích lặp qua từng Cluster VÀ Category
cluster_labels = sorted(df_analysis['Cluster'].unique())
categories_to_analyze = df_agg_cat_macro['Category'].unique()
ped_results_list_cat = []

print(f"Bắt đầu chạy hồi quy (Mô hình 5) cho 3 Cụm x {len(categories_to_analyze)} Categories...")

for cluster in cluster_labels:
    for category in categories_to_analyze:

        df_cat_segment = df_agg_cat_macro[
            (df_agg_cat_macro['Cluster'] == cluster) &
            (df_agg_cat_macro['Category'] == category)
        ].copy()

        # 7.6. Xây dựng mô hình Log-Log Đa biến
        if df_cat_segment.shape[0] > 10: # Cần đủ dữ liệu

            Y = np.log(df_cat_segment['Total_Quantity'])

            X = pd.DataFrame({
                'log_Price_Index': np.log(df_cat_segment['Price_Index']),
                'Promotion': df_cat_segment['Promotion_Campaign'],
                'Weekend': df_cat_segment['Is_Weekend'],
                'Holiday': df_cat_segment['Is_Holiday'],
                'Monthly_Index': df_cat_segment['Monthly_Index']
            })
            X = sm.add_constant(X)

            model_ols = sm.OLS(Y, X).fit()

            ped_value = model_ols.params['log_Price_Index']
            p_value = model_ols.pvalues['log_Price_Index'] # Giữ lại P-Value để lọc

            ped_results_list_cat.append({
                'Category': category,
                'Phân khúc (Cluster)': cluster,
                'PED (β1)': ped_value,
                'P_Value': p_value
            })

        else:
            ped_results_list_cat.append({
                'Category': category,
                'Phân khúc (Cluster)': cluster,
                'PED (β1)': np.nan,
                'P_Value': np.nan
            })

# 7.7. Hiển thị Bảng kết quả tổng hợp
print("\n--- [BƯỚC 7 - Mô hình 5] Hoàn tất tính toán PED. ---")
df_ped_summary_category = pd.DataFrame(ped_results_list_cat) # Lưu kết quả

# Hiển thị bảng lọc |PED| > 1 (Theo yêu cầu cuối cùng của bạn)
print("\n--- Bảng tóm tắt (Pivot) CHỈ DÀNH CHO KẾT QUẢ CO GIÃN (Elastic) ---")
# RÀNG BUỘC 2: Lọc 1 điều kiện duy nhất: Co giãn (Giá trị tuyệt đối của PED > 1)
df_ped_elastic = df_ped_summary_category[
    (df_ped_summary_category['PED (β1)'].abs() > 1)
]

# Đổi tên cụm
cluster_name_map = { 0: 'Cụm 0', 1: 'Cụm 1', 2: 'Cụm 2' }
df_ped_elastic['Phân khúc'] = df_ped_elastic['Phân khúc (Cluster)'].map(cluster_name_map)

if df_ped_elastic.empty:
    print("Không tìm thấy kết quả nào Co giãn (|PED| > 1).")
else:
    df_pivot_elastic = df_ped_elastic.pivot_table(
        index='Category',
        columns='Phân khúc',
        values='PED (β1)'
    )
    print(df_pivot_elastic.to_markdown(floatfmt=".3f"))
    print("\n(Lưu ý: Chỉ hiển thị các giá trị |PED| > 1, bỏ qua P-Value)")

print("\n--- [GIAI ĐOẠN 2] HOÀN TẤT. ---")
print("Biến df_ped_elastic (chỉ |PED| > 1) đã sẵn sàng.")

# --- BƯỚC 0: IMPORT CÁC THƯ VIỆN CẦN THIẾT ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from IPython.display import display # Để hiển thị DataFrame đẹp hơn

# Thư viện Preprocessing
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

# Thư viện Mô hình Clustering
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.mixture import GaussianMixture

# Thư viện Đánh giá
from sklearn.metrics import silhouette_score, davies_bouldin_score

# Thư viện Hồi quy
import statsmodels.api as sm
import warnings

# [LOGIC MỚI] Bỏ thư viện Scipy Optimize
# import scipy.optimize as opt
# from scipy.optimize import minimize, NonlinearConstraint

# Cài đặt hiển thị
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)
warnings.filterwarnings('ignore')
print("-- [BƯỚC 0] Tất cả thư viện đã được nhập thành công. --")


# --- BƯỚC 1: TẢI VÀ KỸ THUẬT ĐẶC TRƯNG (FEATURE ENGINEERING) ---

print("\n-- [BƯỚC 1] Đang tải dữ liệu và xây dựng đặc trưng... --")
try:
    # [SỬA LỖI] Tải TẤT CẢ 4 tệp cần thiết ngay từ đầu
    df_trans = pd.read_csv('transaction_data.csv')
    df_cust = pd.read_csv('customer_profile.csv')
    df_prod = pd.read_csv('product_master.csv')
    df_macro = pd.read_csv('macro_context.csv')

    # Chuyển đổi kiểu dữ liệu ngày tháng
    df_trans['Date_Time'] = pd.to_datetime(df_trans['Date_Time'])
    df_macro['Date'] = pd.to_datetime(df_macro['Date']).dt.date.astype(str)
    print("Tải 4 tệp dữ liệu thành công.")
except FileNotFoundError:
    print("LỖI: Không tìm thấy 1 trong 4 tệp CSV. Vui lòng đảm bảo 4 tệp (trans, cust, prod, macro) nằm trong cùng thư mục.")
    # exit()

# 1.1. Xây dựng đặc trưng RFM
print("Đang xây dựng đặc trưng RFM...")
snapshot_date = df_trans['Date_Time'].max() + pd.Timedelta(days=1)

rfm_df = df_trans.groupby('Customer_ID').agg(
    Recency=('Date_Time', lambda x: (snapshot_date - x.max()).days),
    Frequency=('Transaction_ID', 'nunique'),
    Monetary=('Total_Paid', 'sum')
).reset_index()

# 1.2. Kết hợp và Xây dựng đặc trưng Hồ sơ (Profile)
print("Đang kết hợp dữ liệu và tạo đặc trưng 'Age'...")
df_analysis = pd.merge(df_cust, rfm_df, on='Customer_ID', how='left')

# Xử lý khách hàng không có giao dịch (nếu có)
df_analysis['Recency'] = df_analysis['Recency'].fillna(999) # Giả định R=999 cho KH không có giao dịch
df_analysis[['Frequency', 'Monetary']] = df_analysis[['Frequency', 'Monetary']].fillna(0)

# Tạo đặc trưng 'Age'
current_year = snapshot_date.year
df_analysis['Age'] = current_year - df_analysis['YoB']

# Xử lý ngoại lệ (Outliers) cho RFM - Sử dụng Capping ở Phân vị 99%
print("Đang xử lý ngoại lệ cho RFM (capping ở Q99)...")
for col in ['Recency', 'Frequency', 'Monetary']:
    cap_value = df_analysis[col].quantile(0.99)
    df_analysis[col] = df_analysis[col].clip(upper=cap_value)

# 1.3. Chọn các đặc trưng cuối cùng cho mô hình
features_to_cluster = [
    'Age', 'Recency', 'Frequency', 'Monetary',  # Số
    'Income level', 'Membership_Tier',          # Xếp hạng
    'Occupation', 'Gender'                      # Danh nghĩa
]
df_model_input = df_analysis[features_to_cluster].copy()
print(f"Hoàn tất BƯỚC 1. Dữ liệu đầu vào có {df_model_input.shape[0]} khách hàng và {df_model_input.shape[1]} đặc trưng.")


# --- BƯỚC 2: TIỀN XỬ LÝ (PREPROCESSING PIPELINE) ---

print("\n-- [BƯỚC 2] Xây dựng Pipeline Mã hóa & Chuẩn hóa... --")

# 2.1. Định nghĩa các nhóm cột
numerical_features = ['Age', 'Recency', 'Frequency', 'Monetary']
income_levels = ['< 2M', '2-5M', '5-10M', '10-20M', '20-50M', '> 50M']
membership_tiers = ['Standard', 'Silver', 'Gold', 'Diamond']
ordinal_features = ['Income level', 'Membership_Tier']
nominal_features = ['Occupation', 'Gender']

# 2.2. Xây dựng các đường ống (pipeline) con
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
ordinal_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder(categories=[income_levels, membership_tiers], handle_unknown='use_encoded_value', unknown_value=-1))
])
nominal_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

# 2.3. Kết hợp các pipeline con bằng ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_features),
        ('ord', ordinal_transformer, ordinal_features),
        ('nom', nominal_transformer, nominal_features)
    ],
    remainder='passthrough'
)

# 2.4. Áp dụng preprocessor
X_scaled = preprocessor.fit_transform(df_model_input)
print("Pipeline tiền xử lý hoàn tất.")

# --- BƯỚC 3: XÁC ĐỊNH SỐ CỤM TỐI ƯU (K) ---
# (Bỏ qua phần này để chạy nhanh hơn, giả định K=3)
print("\n-- [BƯỚC 3] Bỏ qua (Giả định K=3)... --")

# --- BƯỚC 4: HUẤN LUYỆN VÀ ĐÁNH GIÁ MÔ HÌNH K-MEANS ---

print("\n-- [BƯỚC 4] Huấn luyện & Đánh giá mô hình K-Means Clustering... --")
N_CLUSTERS = 3
model_name = "K-Means"
model = KMeans(n_clusters=N_CLUSTERS, init='k-means++', random_state=42, n_init=10)
print(f"\nĐang huấn luyện mô hình {model_name}...")
labels = model.fit_predict(X_scaled)
labels_dict = {model_name: labels} # Lưu nhãn
print("Hoàn tất BƯỚC 4.")


# --- BƯỚC 5: GIẢM CHIỀU DỮ LIỆU BẰNG PCA & TRỰC QUAN HÓA CỤM K-MEANS ---
# (Bỏ qua phần này để chạy nhanh hơn)
print("\n-- [BƯỚC 5] Bỏ qua (Không vẽ biểu đồ PCA)... --")

# --- BƯỚC 6: PHÂN TÍCH HỒ SƠ KHÁCH HÀNG THEO CỤM ---

print("\n-- [BƯỚC 6] Đang phân tích hồ sơ khách hàng theo cụm... --")
df_analysis['Cluster'] = labels_dict["K-Means"]
print("Hoàn tất BƯỚC 6.")


# ##################################################################
# --- BƯỚC 7 (Mô hình 5): TÍNH PED (LOGIC ĐÚNG) ---
# Logic mới: log(Q_Category) ~ log(Price_Index_Category) + Controls
# ##################################################################

print("\n\n--- [BƯỚC 7 - Mô hình 5] Đang tính PED (Mô hình Category + Price Index)... ---")

# 7.1. Chuẩn bị dữ liệu (df_trans, df_prod, df_analysis đã có trong bộ nhớ)
print("Đang chuẩn bị dữ liệu...")
df_trans_with_cat = pd.merge(df_trans, df_prod[['Product_ID', 'Category']], on='Product_ID', how='left')
df_full_segmented = pd.merge(
    df_trans_with_cat,
    df_analysis[['Customer_ID', 'Cluster']],
    on='Customer_ID',
    how='left'
)
df_full_segmented = df_full_segmented.dropna(subset=['Cluster', 'Category'])
df_full_segmented = df_full_segmented[df_full_segmented['Quantity'] > 0]
df_full_segmented['Date'] = pd.to_datetime(df_full_segmented['Date_Time']).dt.date.astype(str)
df_full_segmented['Total_List_Price'] = df_full_segmented['Quantity'] * df_full_segmented['Unit_Price_Listed']

# Thêm cột 'Effective_Price' vào df_full_segmented
df_full_segmented['Effective_Price'] = df_full_segmented['Total_Paid'] / df_full_segmented['Quantity']

# 7.2. Tổng hợp theo Date, Cluster, VÀ CATEGORY
print("Đang tổng hợp dữ liệu (Lấy TỔNG Q, TỔNG Paid, TỔNG List) theo Category...")
df_agg_cat = df_full_segmented.groupby(['Date', 'Cluster', 'Category']).agg(
    Total_Quantity=('Quantity', 'sum'),
    Total_Paid_Agg=('Total_Paid', 'sum'),
    Total_List_Price_Agg=('Total_List_Price', 'sum')
).reset_index()

# 7.3. [LOGIC MỚI] Tạo biến "Price_Index" (cho từng Category)
df_agg_cat = df_agg_cat[df_agg_cat['Total_List_Price_Agg'] > 0]
df_agg_cat['Price_Index'] = df_agg_cat['Total_Paid_Agg'] / df_agg_cat['Total_List_Price_Agg']
df_agg_cat = df_agg_cat[df_agg_cat['Price_Index'] > 0]
print("Đã tạo 'Price_Index' (Total_Paid / Total_List_Price) cho từng Category.")

# 7.4. Merge với df_macro để lấy biến kiểm soát
df_agg_cat['Date'] = df_agg_cat['Date'].astype(str)
df_agg_cat_macro = pd.merge(
    df_agg_cat,
    df_macro[['Date', 'Promotion_Campaign', 'Is_Weekend', 'Is_Holiday', 'Monthly_Index']],
    on='Date',
    how='left'
)
print("Đã thêm các biến kiểm soát (Promotion, Weekend, Holiday, Monthly_Index).")

# 7.5. Phân tích lặp qua từng Cluster VÀ Category
cluster_labels = sorted(df_analysis['Cluster'].unique())
categories_to_analyze = df_agg_cat_macro['Category'].unique()
ped_results_list_cat = []

print(f"Bắt đầu chạy hồi quy (Mô hình 5) cho 3 Cụm x {len(categories_to_analyze)} Categories...")

for cluster in cluster_labels:
    for category in categories_to_analyze:

        df_cat_segment = df_agg_cat_macro[
            (df_agg_cat_macro['Cluster'] == cluster) &
            (df_agg_cat_macro['Category'] == category)
        ].copy()

        # 7.6. Xây dựng mô hình Log-Log Đa biến
        if df_cat_segment.shape[0] > 10: # Cần đủ dữ liệu

            Y = np.log(df_cat_segment['Total_Quantity'])

            X = pd.DataFrame({
                'log_Price_Index': np.log(df_cat_segment['Price_Index']),
                'Promotion': df_cat_segment['Promotion_Campaign'],
                'Weekend': df_cat_segment['Is_Weekend'],
                'Holiday': df_cat_segment['Is_Holiday'],
                'Monthly_Index': df_cat_segment['Monthly_Index']
            })
            X = sm.add_constant(X)

            model_ols = sm.OLS(Y, X).fit()

            ped_value = model_ols.params['log_Price_Index']
            p_value = model_ols.pvalues['log_Price_Index'] # [SỬA LỖI] Giữ lại P-Value

            ped_results_list_cat.append({
                'Category': category,
                'Phân khúc (Cluster)': cluster,
                'PED (β1)': ped_value,
                'P_Value': p_value # [SỬA LỖI] Giữ lại P-Value
            })

        else:
            ped_results_list_cat.append({
                'Category': category,
                'Phân khúc (Cluster)': cluster,
                'PED (β1)': np.nan,
                'P_Value': np.nan # [SỬA LỖI] Giữ lại P-Value
            })

# 7.7. Hiển thị Bảng kết quả tổng hợp
print("\n--- [BƯỚC 7 - Mô hình 5] Hoàn tất tính toán PED. ---")
df_ped_summary_category = pd.DataFrame(ped_results_list_cat) # Lưu kết quả

# Hiển thị bảng lọc |PED| > 1 (Theo yêu cầu cuối cùng của bạn)
print("\n--- Bảng tóm tắt (Pivot) CHỈ DÀNH CHO KẾT QUẢ CO GIÃN (Elastic) ---")
# RÀNG BUỘC 2: Lọc 1 điều kiện duy nhất: Co giãn (Giá trị tuyệt đối của PED > 1)
df_ped_elastic = df_ped_summary_category[
    (df_ped_summary_category['PED (β1)'].abs() > 1)
]

# Đổi tên cụm
cluster_name_map = { 0: 'Cụm 0', 1: 'Cụm 1', 2: 'Cụm 2' }
df_ped_elastic['Phân khúc'] = df_ped_elastic['Phân khúc (Cluster)'].map(cluster_name_map)

if df_ped_elastic.empty:
    print("Không tìm thấy kết quả nào Co giãn (|PED| > 1).")
else:
    df_pivot_elastic = df_ped_elastic.pivot_table(
        index='Category',
        columns='Phân khúc',
        values='PED (β1)'
    )
    print(df_pivot_elastic.to_markdown(floatfmt=".3f"))
    print("\n(Lưu ý: Chỉ hiển thị các giá trị |PED| > 1, bỏ qua P-Value)")


# ##################################################################
# --- BƯỚC 8-11: TỐI ƯU HÓA (OPTIMIZATION) ---
# [LOGIC MỚI] Quay lại Grid Search + 7 Ràng buộc
# ##################################################################

print("\n\n--- [BƯỚC 8-10] Đang định nghĩa Hàm Tối ưu hóa (Grid Search)... ---")

# RÀNG BUỘC 6: Bảo vệ Thị phần (Không giảm quá 15%)
MAX_QUANTITY_DROP_PCT = 0.15
print(f"    [Ràng buộc 6] Ràng buộc sụt giảm sản lượng tối đa: {MAX_QUANTITY_DROP_PCT:.0%}")

# [LOGIC MỚI] RÀNG BUỘC 7: "Business Sense" - Giới hạn tăng giá tối đa
MAX_PRICE_INCREASE_PCT = 0.20 # Tăng tối đa 20%
print(f"    [Ràng buộc 7] Ràng buộc tăng giá tối đa: {MAX_PRICE_INCREASE_PCT:.0%}")


# [BƯỚC 8] Hàm chuẩn bị dữ liệu
def prepare_base_data_optimization():
    print("    [B8] Đang chuẩn bị Dữ liệu Nền (P_base, Q_base, COGS, PED)...")
    try:
        # 1. P_base (Giá bán thực tế TB) cho mỗi SKU
        # (df_full_segmented đã được tạo ở BƯỚC 7)
        df_p_base = df_full_segmented.groupby('Product_ID')['Effective_Price'].mean().to_frame('P_base')

        # 2. Q_base (Tổng sản lượng cơ sở) cho mỗi SKU và từng Cụm
        df_q_total_base = df_full_segmented.groupby('Product_ID')['Quantity'].sum().to_frame('Q_total_base')
        df_q_base_pivot = df_full_segmented.groupby(['Product_ID', 'Cluster'])['Quantity'].sum().unstack(fill_value=0)
        df_q_base_pivot.columns = [f'Q_base_{col}' for col in df_q_base_pivot.columns]

        # 3. Lấy COGS cũ (Cần df_prod)
        df_cogs = df_prod.set_index('Product_ID')[['COGS', 'Category']]

        # 4. [LOGIC MỚI] Ánh xạ PED (từ BƯỚC 7) theo Category
        # (df_ped_elastic đã được tạo ở BƯỚC 7)
        print("    [B8] Đang ánh xạ PED từ BƯỚC 7 (chỉ lấy |PED| > 1)...")

        # RÀNG BUỘC LỌC: Chỉ lấy PED có |PED| > 1

        # Pivot các PED "Elastic"
        df_ped_pivot = df_ped_elastic.pivot_table(
            index='Category',
            columns='Phân khúc (Cluster)', # Dùng Cluster (số)
            values='PED (β1)'
        )
        df_ped_pivot.columns = [f'PED_{col}' for col in df_ped_pivot.columns]

        # Gắn PED vào bảng COGS (theo Category)
        # [SỬA LỖI] Sửa lại logic merge: Dùng left_on='Category' và right_index=True
        df_cogs_with_ped = pd.merge(df_cogs, df_ped_pivot, left_on='Category', right_index=True, how='left')

        # ##########################################################
        # [LOGIC MỚI] RÀNG BUỘC 3b: (Business Sense)
        # Gán PED = -1.0 (Unit Elastic) cho các phân khúc "Inelastic" (NaN)
        # ##########################################################
        ped_cols = ['PED_0', 'PED_1', 'PED_2']
        df_cogs_with_ped[ped_cols] = df_cogs_with_ped[ped_cols].fillna(-1.0)
        print("          -> Đã gán PED = -1.0 (Unit Elastic) cho các phân khúc 'Inelastic' (NaN).")

        # 5. Hợp nhất tất cả
        df_base = pd.concat([
            df_p_base, df_q_total_base, df_q_base_pivot, df_cogs_with_ped
        ], axis=1)

        df_base = df_base.dropna(subset=['P_base', 'Q_total_base'])
        print(f"    [B8] Đã chuẩn bị xong Dữ liệu Nền cho {len(df_base)} SKUs.")
        return df_base.copy()

    except NameError as e:
        print(f"    [B8] LỖI NameError: {e}. Vui lòng đảm bảo BƯỚC 1-7 (đặc biệt là df_trans, df_analysis, df_prod, df_ped_summary_category) đã chạy.")
        return None
    except Exception as e:
        print(f"    [B8] LỖI: {e}")
        return None

# [BƯỚC 10] Hàm tính toán cho 1 SKU (Logic 1 Giá, Grid Search)
def optimize_sku_gridsearch(row):
    # Lấy dữ liệu nền
    p_base = row['P_base']
    q_total_base = row['Q_total_base']
    cogs_new = row['COGS_new']

    clusters = [0, 1, 2]
    q_base = {}
    ped = {}

    # RÀNG BUỘC 3: Gán Thị phần và PED
    for c in clusters:
        q_base[c] = row.get(f'Q_base_{c}', 0)
        ped[c] = row.get(f'PED_{c}', -1.0) # Lấy PED (Nếu lỗi, mặc định -1.0)

    profit_at_p_base = 0.0
    q_at_p_base = 0.0

    # 1. Tính Profit_at_P_base (với COGS_new)
    for c in clusters:
        profit_at_p_base += (p_base - cogs_new) * q_base[c]
        q_at_p_base += q_base[c]

    # 2. Định nghĩa Ràng buộc
    # RÀNG BUỘC 4 (Chi phí): P >= COGS_new
    p_min = max(p_base, cogs_new)

    # RÀNG BUỘC 7 ("Business Sense"): Tăng giá tối đa 20%
    p_max = p_base * (1 + MAX_PRICE_INCREASE_PCT)

    # RÀNG BUỘC 6 (Thị phần):
    q_min_allowed = q_at_p_base * (1 - MAX_QUANTITY_DROP_PCT)

    if p_min > p_max:
        return pd.Series({'P_optimal': p_base, 'Profit_optimal': profit_at_p_base, 'Q_optimal': q_at_p_base, 'Profit_at_P_base': profit_at_p_base, 'Status': f'Lỗi: COGS_new ({cogs_new:,.0f}) > P_max ({p_max:,.0f})'})

    price_grid = np.linspace(p_min, p_max, 100) # Quét 100 điểm

    best_profit = profit_at_p_base
    best_p = p_base
    best_q = q_at_p_base

    # 3. Chạy Grid Search (Tìm Profit Max)
    for p_new in price_grid:
        # Bắt đầu từ p_min (đã bao gồm p_base)

        total_profit_new = 0
        total_q_new = 0

        # RÀNG BUỘC 1, 2, 5 (Hàm cầu, PED, 1 Giá)
        for c in clusters:
            if q_base[c] == 0: continue
            # Công thức Q_new
            q_new_c = q_base[c] * (p_new / p_base) ** ped[c]
            # Công thức Profit_new
            profit_new_c = (p_new - cogs_new) * q_new_c

            total_profit_new += profit_new_c
            total_q_new += q_new_c

        # RÀNG BUỘC 6 (Thị phần)
        if total_q_new < q_min_allowed:
            continue # Vi phạm, bỏ qua mức giá này

        # HÀM MỤC TIÊU: Maximize Profit
        # [SỬA LỖI LOGIC] Phải dùng >= để ghi đè giá trị p_base
        if total_profit_new >= best_profit:
            best_profit, best_p, best_q = total_profit_new, p_new, total_q_new

    return pd.Series({'P_optimal': best_p, 'Profit_optimal': best_profit, 'Q_optimal': best_q, 'Profit_at_P_base': profit_at_p_base, 'Status': 'Thành công'})

# [BƯỚC 9 & 11] Hàm chạy chính
def run_optimization(cogs_input_dict, df_base_data):
    if df_base_data is None:
        print("    [B11] LỖI: Dữ liệu nền (df_base_data) rỗng.")
        return

    df_base = df_base_data.copy()
    df_base['COGS_new'] = df_base['COGS']
    if cogs_input_dict:
        cogs_new_series = pd.Series(cogs_input_dict)
        cogs_new_series.name = 'COGS_new_override'
        df_base = df_base.merge(cogs_new_series, left_index=True, right_index=True, how='left')
        df_base['COGS_new'] = df_base['COGS_new_override'].fillna(df_base['COGS_new'])
        df_base = df_base.drop(columns=['COGS_new_override'])
        print(f"    [B9] Đã áp dụng COGS_new cho {len(cogs_input_dict)} SKUs.")
    else:
        print("    [B9] Không có COGS_new nào được nhập. Dùng COGS hiện tại.")

    print(f"    [B11] Đang chạy Tối ưu hóa (Grid Search) cho {len(df_base)} SKUs...")
    results_list = df_base.apply(optimize_sku_gridsearch, axis=1) # Gọi hàm Grid Search

    df_final_results = df_base.join(results_list)

    # Tính toán các chỉ số cải thiện
    df_final_results['Profit_Increase'] = df_final_results['Profit_optimal'] - df_final_results['Profit_at_P_base']
    df_final_results['Profit_Increase_Pct'] = (df_final_results['Profit_Increase'] / df_final_results['Profit_at_P_base']).replace([np.inf, -np.inf], np.nan)
    df_final_results['Q_Drop_Pct'] = (df_final_results['Q_total_base'] - df_final_results['Q_optimal']) / df_final_results['Q_total_base']
    df_final_results['P_Increase_Pct'] = (df_final_results['P_optimal'] - df_final_results['P_base']) / df_final_results['P_base']

    df_final_results = df_final_results.sort_values(by='Profit_Increase', ascending=False)

    columns_to_show = [
        'COGS_new', 'P_base', 'P_optimal', 'Profit_at_P_base', 'Profit_optimal',
        'Profit_Increase', 'Profit_Increase_Pct', 'Q_total_base', 'Q_optimal',
        'Q_Drop_Pct', 'P_Increase_Pct', 'Status'
    ]
    ped_cols_to_show = ['Category', 'PED_0', 'PED_1', 'PED_2']

    print("\n--- KẾT QUẢ TỐI ƯU HÓA GIÁ (ĐÃ SẮP XẾP) ---")
    print(f"(Ràng buộc: Tăng giá tối đa {MAX_PRICE_INCREASE_PCT:.0%}, Sụt giảm Sản lượng tối đa {MAX_QUANTITY_DROP_PCT:.0%})")

    # [SỬA LỖI] Sửa lỗi thụt lề
    display(df_final_results[columns_to_show].style.format({
        'COGS_new': '{:,.0f}', 'P_base': '{:,.0f}', 'P_optimal': '{:,.0f}',
        'Profit_at_P_base': '{:,.0f}', 'Profit_optimal': '{:,.0f}', 'Profit_Increase': '{:,.0f}',
        'Q_total_base': '{:,.0f}', 'Q_optimal': '{:,.0f}',
        'Profit_Increase_Pct': '{:.1%}',
        'Q_Drop_Pct': '{:.1%}',
        'P_Increase_Pct': '{:.1%}'
    }))

    print("\n--- Bảng tra cứu PED đã sử dụng (-1.0 = Giả định Inelastic) ---")
    # [SỬA LỖI] Sửa lỗi format
    ped_format_dict = {
        'PED_0': '{:.3f}',
        'PED_1': '{:.3f}',
        'PED_2': '{:.3f}'
    }
    display(df_final_results[ped_cols_to_show].style.format(ped_format_dict))

# --- CHẠY KHỐI 1 (BƯỚC 0-7) ---
print("--- [BẮT ĐẦU] Chạy BƯỚC 0-7 (Phân khúc và Tính PED)... ---")
# (Toàn bộ code BƯỚC 0-7 chạy ở trên)
print("\n--- [HOÀN TẤT] BƯỚC 0-7. ---")


# --- CHẠY KHỐI 2 (BƯỚC 8-11) ---
print("\n--- [BẮT ĐẦU] Chạy BƯỚC 8-11 (Tối ưu hóa)... ---")
GLOBAL_DF_BASE_DATA = prepare_base_data_optimization()

if GLOBAL_DF_BASE_DATA is not None:
    # ##################################################################
    # BẢNG ĐIỀU KHIỂN INPUT CỦA BẠN
    # ##################################################################
    cogs_input_cua_ban = {
        # === Coffee (Cũ + 6,000) ===
        'CF01_S': 16500,  # (Cũ: 10500)
        'CF01_M': 19500,  # (Cũ: 13500)
        'CF01_L': 22500,  # (Cũ: 16500)
        'CF02_S': 16500,  # (Cũ: 10500)
        'CF02_M': 19500,  # (Cũ: 13500)
        'CF02_L': 22500,  # (Cũ: 16500)
        'CF03_S': 16500,  # (Cũ: 10500)
        'CF03_M': 19500,  # (Cũ: 13500)
        'CF03_L': 22500,  # (Cũ: 16500)

        # === Tea (Cũ + 6,000) ===
        'TE04_S': 18250,  # (Cũ: 12250)
        'TE04_M': 20750,  # (Cũ: 14750)
        'TE04_L': 23250,  # (Cũ: 17250)
        'TE05_S': 18250,  # (Cũ: 12250)
        'TE05_M': 20750,  # (Cũ: 14750)
        'TE05_L': 23250,  # (Cũ: 17250)
        'TE06_S': 18250,  # (Cũ: 12250)
        'TE06_M': 20750,  # (Cũ: 14750)
        'TE06_L': 23250,  # (Cũ: 17250)

        # === Freeze (Cũ + 6,000) ===
        'FR07_S': 23250,  # (Cũ: 17250)
        'FR07_M': 26250,  # (Cũ: 20250)
        'FR07_L': 29250,  # (Cũ: 23250)
        'FR08_S': 23250,  # (Cũ: 17250)
        'FR08_M': 26250,  # (Cũ: 20250)
        'FR08_L': 29250,  # (Cũ: 23250)
        'FR09_S': 23250,  # (Cũ: 17250)
        'FR09_M': 26250,  # (Cũ: 20250)
        'FR09_L': 29250,  # (Cũ: 23250)
    }
    # ##################################################################

    print(f"\n--- [KHỐI 2] Bắt đầu chạy Tối ưu hóa (Grid Search) cho {len(cogs_input_cua_ban)} SKU... ---")
    run_optimization(cogs_input_cua_ban, GLOBAL_DF_BASE_DATA)
else:
    print("\nLỖI: Không thể chạy Tối ưu hóa vì Dữ liệu Nền (BƯỚC 8) đã thất bại.")

print("\n--- [TOÀN BỘ QUY TRÌNH] HOÀN TẤT. ---")

pip install cmdstanpy

# --- [FILE STANDALONE]: DỰ BÁO Q1/2025 VỚI 4 MÔ HÌNH (ĐÃ SỬA LỖI HIỂN THỊ) ---
# Mục tiêu:
# 1. Dùng dữ liệu 2024 để huấn luyện 4 mô hình dự báo Lượng bán (Quantity)
#    dựa trên các yếu tố như Giá, Lễ, Cuối tuần.
# 2. Tạo dữ liệu 90 ngày cho Q1/2025.
# 3. Dự báo Q1/2025 với 2 kịch bản giá.
# 4. Tính toán Doanh thu & Lợi nhuận cho từng kịch bản.
# -----------------------------------------------------------------

# --- BƯỚC 0: IMPORT THƯ VIỆN ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import timedelta
import warnings
from IPython.display import display, Markdown

# Thư viện Preprocessing
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Thư viện 4 Mô hình
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
# from prophet import Prophet # ĐÃ BỎ DO LỖI KỸ THUẬT
# Tắt cảnh báo TensorFlow
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
tf.get_logger().setLevel('ERROR')
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import EarlyStopping

# Thư viện Đánh giá (để tham khảo)
from sklearn.metrics import mean_absolute_error

# Cài đặt
pd.set_option('display.float_format', '{:.2f}'.format)
warnings.filterwarnings('ignore')
print("-- [BƯỚC 0] Tất cả thư viện đã được nhập thành công. --")


# --- [GIẢ ĐỊNH KỊCH BẢN] ---
# Đây là các giả định từ file Tối ưu hóa (Optimization)

# Kịch bản A: Giữ nguyên giá
PRICE_INDEX_A = 0.95

# Kịch bản B: Tăng giá theo Tối ưu hóa
PRICE_INDEX_B = 1.02

# Giả định về Giá trị & Chi phí (để tính lợi nhuận)
AVG_LIST_PRICE_PER_ITEM = 55000 # Giá niêm yết trung bình
NEW_COGS_PER_ITEM = 18000 # Giá vốn mới (sau khi tăng 6k)

# Tính toán giá bán thực tế cho mỗi kịch bản
PRICE_PAID_A = AVG_LIST_PRICE_PER_ITEM * PRICE_INDEX_A
PRICE_PAID_B = AVG_LIST_PRICE_PER_ITEM * PRICE_INDEX_B
print(f"-- [GIẢ ĐỊNH] Kịch bản A (Giữ giá): {PRICE_PAID_A:,.0f} đ / 1 ly")
print(f"-- [GIẢ ĐỊNH] Kịch bản B (Tăng giá): {PRICE_PAID_B:,.0f} đ / 1 ly")
print(f"-- [GIẢ ĐỊNH] Giá vốn mới: {NEW_COGS_PER_ITEM:,.0f} đ / 1 ly")
# ----------------------------------


# --- BƯỚC 1: TẢI VÀ TỔNG HỢP DỮ LIỆU (TẠO BẢNG HUẤN LUYỆN 2024) ---
print("\n-- [BƯỚC 1] Đang tải và tạo Bảng dữ liệu huấn luyện (2024)... --")
try:
    df_trans = pd.read_csv('transaction_data.csv')
    df_prod = pd.read_csv('product_master.csv') # Cần để lấy giá niêm yết
    df_macro = pd.read_csv('macro_context.csv')
except FileNotFoundError:
    print("LỖI: Không tìm thấy tệp CSV. Vui lòng đảm bảo 3 tệp (trans, prod, macro) nằm trong cùng thư mục.")
    # exit()

# Chuyển đổi kiểu dữ liệu
df_trans['Date_Time'] = pd.to_datetime(df_trans['Date_Time'])
df_trans['Date'] = df_trans['Date_Time'].dt.date.astype(str)
df_macro['Date'] = pd.to_datetime(df_macro['Date']).dt.date.astype(str)

# 1.1. Tính toán 'Total_List_Price' cho từng giao dịch
df_trans = pd.merge(
    df_trans,
    df_prod[['Product_ID', 'Unit_Price_List']],
    on='Product_ID',
    how='left'
)
df_trans = df_trans.rename(columns={'Unit_Price_Listed': 'Unit_Price_Recorded', 'Unit_Price_List': 'Unit_Price_Master'})
df_trans['Unit_Price_Master'] = df_trans['Unit_Price_Master'].fillna(df_trans['Unit_Price_Recorded'])
df_trans['Total_List_Price'] = df_trans['Quantity'] * df_trans['Unit_Price_Master']


# 1.2. Tổng hợp (Aggregate) toàn bộ giỏ hàng lên cấp độ HÀNG NGÀY
df_daily_agg = df_trans.groupby('Date').agg(
    Total_Quantity=('Quantity', 'sum'),
    Total_Paid_Agg=('Total_Paid', 'sum'),
    Total_List_Price_Agg=('Total_List_Price', 'sum')
).reset_index()

# 1.3. Tính toán 'Price_Index' (BIẾN NGUYÊN NHÂN CHÍNH)
df_daily_agg = df_daily_agg[df_daily_agg['Total_List_Price_Agg'] > 0]
df_daily_agg['Price_Index'] = df_daily_agg['Total_Paid_Agg'] / df_daily_agg['Total_List_Price_Agg']

# 1.4. Gắn các biến ngoại lai (Macro)
df_train_2024 = pd.merge(
    df_daily_agg,
    df_macro[['Date', 'Is_Weekend', 'Is_Holiday', 'Promotion_Campaign']],
    on='Date',
    how='left'
)

# 1.5. Tạo các đặc trưng thời gian
df_train_2024['Date'] = pd.to_datetime(df_train_2024['Date'])
df_train_2024 = df_train_2024.set_index('Date')
df_train_2024['Month'] = df_train_2024.index.month
df_train_2024['DayOfWeek'] = df_train_2024.index.dayofweek

# 1.6. Final check
df_train_2024 = df_train_2024.dropna()
print(f"Hoàn tất BƯỚC 1. Đã tạo bảng huấn luyện 2024 với {len(df_train_2024)} ngày.")
display(df_train_2024.head())


# --- BƯỚC 2: TẠO DỮ LIỆU TƯƠNG LAI (Q1/2025) ---
print("\n-- [BƯỚC 2] Đang tạo Bảng dữ liệu tương lai (Q1/2025)... --")
N_DAYS_FORECAST = 90
last_date_2024 = df_train_2024.index.max()
future_dates = pd.date_range(start=last_date_2024 + timedelta(days=1), periods=N_DAYS_FORECAST, freq='D')

df_future_2025 = pd.DataFrame(index=future_dates)
df_future_2025['Is_Weekend'] = (df_future_2025.index.dayofweek >= 5).astype(int)
df_future_2025['Month'] = df_future_2025.index.month
df_future_2025['DayOfWeek'] = df_future_2025.index.dayofweek

# Giả định về tương lai:
df_future_2025['Is_Holiday'] = 0
df_future_2025['Promotion_Campaign'] = 0

print(f"Hoàn tất BƯỚC 2. Đã tạo bảng tương lai {N_DAYS_FORECAST} ngày.")
display(df_future_2025.head())


# --- BƯỚC 3: HUẤN LUYỆN VÀ DỰ BÁO VỚI 4 MÔ HÌNH ---
print("\n-- [BƯỚC 3] Bắt đầu huấn luyện và dự báo với 4 mô hình... --")

# 3.1. Định nghĩa Biến Y (Target) và X (Features)
target_col = 'Total_Quantity'
feature_cols = ['Price_Index', 'Is_Weekend', 'Is_Holiday', 'Promotion_Campaign', 'Month', 'DayOfWeek']

Y_train = df_train_2024[target_col]
X_train = df_train_2024[feature_cols]

# 3.2. Tạo 2 kịch bản X_future
# Kịch bản A: Dùng Price_Index cũ
X_future_A = df_future_2025[feature_cols[1:]].copy()
X_future_A['Price_Index'] = PRICE_INDEX_A
X_future_A = X_future_A[feature_cols]

# Kịch bản B: Dùng Price_Index tối ưu
X_future_B = df_future_2025[feature_cols[1:]].copy()
X_future_B['Price_Index'] = PRICE_INDEX_B
X_future_B = X_future_B[feature_cols]

# Lưu trữ kết quả
forecast_results = pd.DataFrame(index=future_dates)
models_summary = {}

# ---------------------------------
# MÔ HÌNH 1: LINEAR REGRESSION
# ---------------------------------
print("\n... [Mô hình 1] Đang chạy Linear Regression ...")
model_lr = LinearRegression()
model_lr.fit(X_train, Y_train)

pred_A_lr = model_lr.predict(X_future_A)
pred_B_lr = model_lr.predict(X_future_B)

forecast_results['LR_A'] = pred_A_lr
forecast_results['LR_B'] = pred_B_lr
models_summary['Linear Regression'] = (pred_A_lr.sum(), pred_B_lr.sum())

# ---------------------------------
# MÔ HÌNH 2: RANDOM FOREST REGRESSOR
# ---------------------------------
print("... [Mô hình 2] Đang chạy Random Forest ...")
model_rf = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
model_rf.fit(X_train, Y_train)

pred_A_rf = model_rf.predict(X_future_A)
pred_B_rf = model_rf.predict(X_future_B)

forecast_results['RF_A'] = pred_A_rf
forecast_results['RF_B'] = pred_B_rf
models_summary['Random Forest'] = (pred_A_rf.sum(), pred_B_rf.sum())

# ---------------------------------
# MÔ HÌNH 3: XGBOOST
# ---------------------------------
print("... [Mô hình 3] Đang chạy XGBoost ...")
model_xgb = XGBRegressor(n_estimators=100, random_state=42, n_jobs=-1, objective='reg:squarederror')
model_xgb.fit(X_train, Y_train)

pred_A_xgb = model_xgb.predict(X_future_A)
pred_B_xgb = model_xgb.predict(X_future_B)

forecast_results['XGB_A'] = pred_A_xgb
forecast_results['XGB_B'] = pred_B_xgb
models_summary['XGBoost'] = (pred_A_xgb.sum(), pred_B_xgb.sum())

# ---------------------------------
# MÔ HÌNH 4: LSTM
# ---------------------------------
print("... [Mô hình 4] Đang chạy LSTM ...")
# 4.1. Chuẩn hóa dữ liệu cho LSTM
scaler_X = MinMaxScaler()
scaler_Y = MinMaxScaler()

X_train_scaled = scaler_X.fit_transform(X_train)
Y_train_scaled = scaler_Y.fit_transform(Y_train.values.reshape(-1, 1))

# 4.2. Định hình lại dữ liệu
X_train_lstm = X_train_scaled.reshape((X_train_scaled.shape[0], 1, X_train_scaled.shape[1]))

# 4.3. Xây dựng mô hình
model_lstm = Sequential()
model_lstm.add(LSTM(50, activation='relu', input_shape=(X_train_lstm.shape[1], X_train_lstm.shape[2])))
model_lstm.add(Dense(1))
model_lstm.compile(optimizer='adam', loss='mse')

# 4.4. Huấn luyện
early_stop = EarlyStopping(monitor='loss', patience=5, verbose=0)
model_lstm.fit(X_train_lstm, Y_train_scaled,
               epochs=20,
               batch_size=32,
               verbose=0,
               callbacks=[early_stop])

# 4.5. Chuẩn bị dữ liệu tương lai
X_future_A_scaled = scaler_X.transform(X_future_A)
X_future_B_scaled = scaler_X.transform(X_future_B)

X_future_A_lstm = X_future_A_scaled.reshape((X_future_A_scaled.shape[0], 1, X_future_A_scaled.shape[1]))
X_future_B_lstm = X_future_B_scaled.reshape((X_future_B_scaled.shape[0], 1, X_future_B_scaled.shape[1]))

# 4.6. Dự báo
pred_A_lstm_scaled = model_lstm.predict(X_future_A_lstm, verbose=0)
pred_B_lstm_scaled = model_lstm.predict(X_future_B_lstm, verbose=0)

# 4.7. Chuyển đổi ngược
pred_A_lstm = scaler_Y.inverse_transform(pred_A_lstm_scaled).flatten()
pred_B_lstm = scaler_Y.inverse_transform(pred_B_lstm_scaled).flatten()

forecast_results['LSTM_A'] = pred_A_lstm
forecast_results['LSTM_B'] = pred_B_lstm
models_summary['LSTM'] = (pred_A_lstm.sum(), pred_B_lstm.sum())

print("\n--- [HOÀN TẤT] Đã chạy xong 4 mô hình! ---")


# --- BƯỚC 4: TỔNG HỢP KẾT QUẢ VÀ TÍNH LỢI NHUẬN ---
print("\n-- [BƯỚC 4] Đang tổng hợp kết quả và tính toán Lợi nhuận... --")

df_summary_report = []

for model_name, (total_q_a, total_q_b) in models_summary.items():
    if total_q_a == 0 and total_q_b == 0:
        continue

    # --- Kịch bản A (Giữ giá) ---
    revenue_A = total_q_a * PRICE_PAID_A
    profit_A = total_q_a * (PRICE_PAID_A - NEW_COGS_PER_ITEM)

    # --- Kịch bản B (Tăng giá) ---
    revenue_B = total_q_b * PRICE_PAID_B
    profit_B = total_q_b * (PRICE_PAID_B - NEW_COGS_PER_ITEM)

    # --- Thay đổi ---
    profit_change = profit_B - profit_A

    df_summary_report.append({
        "Model": model_name,
        "Total_Profit_A (Giữ giá)": profit_A,
        "Total_Profit_B (Tăng giá)": profit_B,
        "Lợi nhuận Tăng/Giảm": profit_change,
        "Total_Quantity_A": total_q_a,
        "Total_Quantity_B": total_q_b
    })

df_final_report = pd.DataFrame(df_summary_report).set_index("Model")
df_final_report = df_final_report.sort_values(by="Lợi nhuận Tăng/Giảm", ascending=False)

# Hiển thị kết quả
display(Markdown("\n" + "="*50))
display(Markdown("📊 BÁO CÁO TỔNG HỢP DỰ BÁO LỢI NHUẬN Q1/2025 (4 MÔ HÌNH)"))
display(Markdown(f"Dự báo cho {N_DAYS_FORECAST} ngày (Q1/2025) khi COGS mới là {NEW_COGS_PER_ITEM:,.0f} đ/ly."))
display(Markdown("="*50 + "\n"))

# Format cho đẹp
format_dict = {
    "Total_Profit_A (Giữ giá)": "{:,.0f} đ",
    "Total_Profit_B (Tăng giá)": "{:,.0f} đ",
    "Lợi nhuận Tăng/Giảm": "{:,.0f} đ",
    "Total_Quantity_A": "{:,.0f} ly",
    "Total_Quantity_B": "{:,.0f} ly"
}
# [SỬA LỖI] Dùng display() với .style, không dùng print()
display(df_final_report.style.format(format_dict).background_gradient(cmap='RdYlGn', subset=['Lợi nhuận Tăng/Giảm']))


# --- BƯỚC 5: TRỰC QUAN HÓA KẾT QUẢ ---
print("\n-- [BƯỚC 5] Đang vẽ biểu đồ kết quả... --")

# Lấy kết quả từ mô hình tốt nhất (ví dụ: XGBoost)
best_model_name = 'XGBoost'
best_model_prefix = 'XGB'

plt.figure(figsize=(15, 7))
forecast_results[f'{best_model_prefix}_A'].plot(label=f'Kịch bản A: Giữ giá (Lượng bán)', style='b--')
forecast_results[f'{best_model_prefix}_B'].plot(label=f'Kịch bản B: Tăng giá (Lượng bán)', style='g-')
plt.title(f'Dự báo Lượng bán Q1/2025 (Sử dụng mô hình: {best_model_name})')
plt.ylabel('Tổng lượng bán hàng ngày')
plt.xlabel('Ngày')
plt.legend()
plt.grid(True)
plt.savefig('forecast_comparison_chart_4_models.png')
print("Hoàn tất. Đã lưu biểu đồ vào 'forecast_comparison_chart_4_models.png'.")

# --- [FILE STANDALONE]: ĐÁNH GIÁ MODEL (R2, MAPE) & DỰ BÁO KỊCH BẢN ---
# Giai đoạn A: Đánh giá model trên dữ liệu 2024
# Giai đoạn B: Dự báo 2 kịch bản cho Q1/2025
# -----------------------------------------------------------------

# --- BƯỚC 0: IMPORT THƯ VIỆN ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import timedelta
import warnings
from IPython.display import display, Markdown

# Thư viện Preprocessing
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Thư viện 4 Mô hình
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
# Tắt cảnh báo TensorFlow
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
tf.get_logger().setLevel('ERROR')
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import EarlyStopping

# [MỚI] Thư viện Đánh giá
from sklearn.metrics import r2_score, mean_absolute_error, mean_absolute_percentage_error, mean_squared_error

# Cài đặt
pd.set_option('display.float_format', '{:.2f}'.format)
warnings.filterwarnings('ignore')
print("-- [BƯỚC 0] Tất cả thư viện đã được nhập thành công. --")


# --- [GIẢ ĐỊNH KỊCH BẢN] ---
# (Các giả định này dùng cho Giai đoạn B)
PRICE_INDEX_A = 0.95
PRICE_INDEX_B = 1.02
AVG_LIST_PRICE_PER_ITEM = 55000
NEW_COGS_PER_ITEM = 18000

PRICE_PAID_A = AVG_LIST_PRICE_PER_ITEM * PRICE_INDEX_A
PRICE_PAID_B = AVG_LIST_PRICE_PER_ITEM * PRICE_INDEX_B
print(f"-- [GIẢ ĐỊNH] Kịch bản A (Giữ giá): {PRICE_PAID_A:,.0f} đ / 1 ly")
print(f"-- [GIẢ ĐỊNH] Kịch bản B (Tăng giá): {PRICE_PAID_B:,.0f} đ / 1 ly")
print(f"-- [GIẢ ĐỊNH] Giá vốn mới: {NEW_COGS_PER_ITEM:,.0f} đ / 1 ly")
# ----------------------------------


# --- BƯỚC 1: TẢI VÀ TỔNG HỢP DỮ LIỆU (TẠO BẢNG HUẤN LUYỆN 2024) ---
print("\n-- [BƯỚC 1] Đang tải và tạo Bảng dữ liệu huấn luyện (2024)... --")
try:
    df_trans = pd.read_csv('transaction_data.csv')
    df_prod = pd.read_csv('product_master.csv') # Cần để lấy giá niêm yết
    df_macro = pd.read_csv('macro_context.csv')
except FileNotFoundError:
    print("LỖI: Không tìm thấy tệp CSV. Vui lòng đảm bảo 3 tệp (trans, prod, macro) nằm trong cùng thư mục.")
    # exit()

# (Thực hiện các bước chuẩn bị dữ liệu như trước)
df_trans['Date_Time'] = pd.to_datetime(df_trans['Date_Time'])
df_trans['Date'] = df_trans['Date_Time'].dt.date.astype(str)
df_macro['Date'] = pd.to_datetime(df_macro['Date']).dt.date.astype(str)

df_trans = pd.merge(
    df_trans,
    df_prod[['Product_ID', 'Unit_Price_List']],
    on='Product_ID',
    how='left'
)
df_trans = df_trans.rename(columns={'Unit_Price_Listed': 'Unit_Price_Recorded', 'Unit_Price_List': 'Unit_Price_Master'})
df_trans['Unit_Price_Master'] = df_trans['Unit_Price_Master'].fillna(df_trans['Unit_Price_Recorded'])
df_trans['Total_List_Price'] = df_trans['Quantity'] * df_trans['Unit_Price_Master']

df_daily_agg = df_trans.groupby('Date').agg(
    Total_Quantity=('Quantity', 'sum'),
    Total_Paid_Agg=('Total_Paid', 'sum'),
    Total_List_Price_Agg=('Total_List_Price', 'sum')
).reset_index()

df_daily_agg = df_daily_agg[df_daily_agg['Total_List_Price_Agg'] > 0]
df_daily_agg['Price_Index'] = df_daily_agg['Total_Paid_Agg'] / df_daily_agg['Total_List_Price_Agg']

df_train_2024_full = pd.merge(
    df_daily_agg,
    df_macro[['Date', 'Is_Weekend', 'Is_Holiday', 'Promotion_Campaign']],
    on='Date',
    how='left'
)

df_train_2024_full['Date'] = pd.to_datetime(df_train_2024_full['Date'])
df_train_2024_full = df_train_2024_full.set_index('Date')
df_train_2024_full['Month'] = df_train_2024_full.index.month
df_train_2024_full['DayOfWeek'] = df_train_2024_full.index.dayofweek

df_train_2024_full = df_train_2024_full.dropna()
print(f"Hoàn tất BƯỚC 1. Đã tạo bảng dữ liệu 2024 (full) với {len(df_train_2024_full)} ngày.")


# --- GIAI ĐOẠN A: ĐÁNH GIÁ MÔ HÌNH (TRÊN DỮ LIỆU 2024) ---

print("\n\n" + "="*50)
print(" GIAI ĐOẠN A: ĐÁNH GIÁ MÔ HÌNH (R2, MAPE) TRÊN DỮ LIỆU 2024")
print("="*50)

# --- BƯỚC 2: CHIA DỮ LIỆU 2024 THÀNH TẬP TRAIN VÀ TEST ---
print("\n-- [BƯỚC 2] Đang chia dữ liệu 2024 thành Train (10 tháng) và Test (2 tháng)... --")
split_date = '2024-11-01'
train_data = df_train_2024_full.loc[df_train_2024_full.index < split_date]
test_data = df_train_2024_full.loc[df_train_2024_full.index >= split_date]

target_col = 'Total_Quantity'
feature_cols = ['Price_Index', 'Is_Weekend', 'Is_Holiday', 'Promotion_Campaign', 'Month', 'DayOfWeek']

Y_train = train_data[target_col]
X_train = train_data[feature_cols]
Y_test = test_data[target_col]
X_test = test_data[feature_cols]

print(f" - Kích thước tập Train: {len(X_train)} ngày")
print(f" - Kích thước tập Test: {len(X_test)} ngày")

# --- BƯỚC 3: HUẤN LUYỆN, DỰ BÁO (TEST SET) VÀ TÍNH TOÁN CHỈ SỐ ---
print("\n-- [BƯỚC 3] Đang huấn luyện và đánh giá 4 mô hình trên tập Test... --")

evaluation_results = []
test_predictions = pd.DataFrame(index=Y_test.index)
test_predictions['Actual'] = Y_test

def calculate_metrics(model_name, y_true, y_pred):
    r2 = r2_score(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    mape = mean_absolute_percentage_error(y_true, y_pred) * 100
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))

    print(f"... Hoàn tất: {model_name} (R2: {r2:.2f}, MAPE: {mape:.2f}%)")
    evaluation_results.append({
        "Model": model_name,
        "R-squared": r2,
        "MAPE (%)": mape,
        "MAE (ly)": mae,
        "RMSE (ly)": rmse
    })
    return y_pred

# --- 4 Models ---
# 1. Linear Regression
model_lr = LinearRegression()
model_lr.fit(X_train, Y_train)
pred_lr = model_lr.predict(X_test)
test_predictions['LR'] = calculate_metrics("Linear Regression", Y_test, pred_lr)

# 2. Random Forest
model_rf = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
model_rf.fit(X_train, Y_train)
pred_rf = model_rf.predict(X_test)
test_predictions['RF'] = calculate_metrics("Random Forest", Y_test, pred_rf)

# 3. XGBoost
model_xgb = XGBRegressor(n_estimators=100, random_state=42, n_jobs=-1, objective='reg:squarederror')
model_xgb.fit(X_train, Y_train)
pred_xgb = model_xgb.predict(X_test)
test_predictions['XGB'] = calculate_metrics("XGBoost", Y_test, pred_xgb)

# 4. LSTM
scaler_X_eval = MinMaxScaler()
scaler_Y_eval = MinMaxScaler()
X_train_scaled_eval = scaler_X_eval.fit_transform(X_train)
Y_train_scaled_eval = scaler_Y_eval.fit_transform(Y_train.values.reshape(-1, 1))
X_test_scaled_eval = scaler_X_eval.transform(X_test)

X_train_lstm_eval = X_train_scaled_eval.reshape((X_train_scaled_eval.shape[0], 1, X_train_scaled_eval.shape[1]))
X_test_lstm_eval = X_test_scaled_eval.reshape((X_test_scaled_eval.shape[0], 1, X_test_scaled_eval.shape[1]))

model_lstm = Sequential()
model_lstm.add(LSTM(50, activation='relu', input_shape=(X_train_lstm_eval.shape[1], X_train_lstm_eval.shape[2])))
model_lstm.add(Dense(1))
model_lstm.compile(optimizer='adam', loss='mse')
early_stop = EarlyStopping(monitor='loss', patience=5, verbose=0)
model_lstm.fit(X_train_lstm_eval, Y_train_scaled_eval, epochs=20, batch_size=32, verbose=0, callbacks=[early_stop])

pred_lstm_scaled = model_lstm.predict(X_test_lstm_eval, verbose=0)
pred_lstm = scaler_Y_eval.inverse_transform(pred_lstm_scaled).flatten()
test_predictions['LSTM'] = calculate_metrics("LSTM", Y_test, pred_lstm)

# --- BƯỚC 4: BÁO CÁO ĐÁNH GIÁ (R2, MAPE) ---
df_evaluation_report = pd.DataFrame(evaluation_results).set_index("Model")
df_evaluation_report = df_evaluation_report.sort_values(by="MAPE (%)", ascending=True)

display(Markdown("\n" + "="*50))
display(Markdown("📊 BÁO CÁO ĐÁNH GIÁ MÔ HÌNH (trên tập Test Nov-Dec 2024)"))
display(Markdown("="*50 + "\n"))
display(df_evaluation_report.style.format({
    "R-squared": "{:.3f}",
    "MAPE (%)": "{:.2f}%",
    "MAE (ly)": "{:,.1f}",
    "RMSE (ly)": "{:,.1f}"
}).background_gradient(cmap='RdYlGn_r', subset=['MAPE (%)']))


# --- BƯỚC 5: TRỰC QUAN HÓA KẾT QUẢ ĐÁNH GIÁ (CHI TIẾT 4 MODEL) ---
print("\n-- [BƯỚC 5] Đang trực quan hóa chi tiết 4 model (Actual vs Predicted)... --")

fig, axes = plt.subplots(4, 1, figsize=(15, 20), sharex=True)
fig.suptitle('ĐÁNH GIÁ CHI TIẾT 4 MODEL (Tập Test Nov-Dec 2024)', fontsize=16, y=1.02)

model_names = [
    ("Linear Regression", "LR"),
    ("Random Forest", "RF"),
    ("XGBoost", "XGB"),
    ("LSTM", "LSTM")
]

for i, (full_name, short_name) in enumerate(model_names):
    ax = axes[i]
    test_predictions['Actual'].plot(ax=ax, label='Sản lượng Thực tế (Actual)', style='k-', linewidth=2)
    test_predictions[short_name].plot(ax=ax, label=f'Dự báo ({full_name})', style='r--', linewidth=2)

    # Lấy MAPE từ bảng báo cáo
    mape_score = df_evaluation_report.loc[full_name]["MAPE (%)"]

    ax.set_title(f'{i+1}. {full_name} (MAPE: {mape_score:.2f}%)')
    ax.set_ylabel('Tổng lượng bán hàng ngày')
    ax.legend()
    ax.grid(True)

plt.xlabel('Ngày')
plt.tight_layout()
plt.savefig('evaluation_chart_grid_4_models.png')
print("Hoàn tất. Đã lưu biểu đồ lưới vào 'evaluation_chart_grid_4_models.png'.")
plt.show()


# --- GIAI ĐOẠN B: DỰ BÁO KỊCH BẢN (CHO Q1/2025) ---

print("\n\n" + "="*50)
print(" GIAI ĐOẠN B: DỰ BÁO KỊCH BẢN (CHO Q1/2025)")
print("="*50)

# --- BƯỚC 6: HUẤN LUYỆN LẠI TRÊN TOÀN BỘ DỮ LIỆU 2024 VÀ DỰ BÁO ---
print("\n-- [BƯỚC 6] Đang huấn luyện lại 4 mô hình trên TOÀN BỘ dữ liệu 2024... --")

# Dữ liệu huấn luyện (full)
Y_train_full = df_train_2024_full[target_col]
X_train_full = df_train_2024_full[feature_cols]

# Dữ liệu tương lai (Q1/2025)
df_future_2025 = pd.DataFrame(index=pd.date_range(start='2025-01-01', periods=90, freq='D'))
df_future_2025['Is_Weekend'] = (df_future_2025.index.dayofweek >= 5).astype(int)
df_future_2025['Month'] = df_future_2025.index.month
df_future_2025['DayOfWeek'] = df_future_2025.index.dayofweek
df_future_2025['Is_Holiday'] = 0
df_future_2025['Promotion_Campaign'] = 0

# Tạo 2 kịch bản X_future
X_future_A = df_future_2025.copy()
X_future_A['Price_Index'] = PRICE_INDEX_A
X_future_A = X_future_A[feature_cols]

X_future_B = df_future_2025.copy()
X_future_B['Price_Index'] = PRICE_INDEX_B
X_future_B = X_future_B[feature_cols]

# Lưu trữ kết quả
forecast_results = pd.DataFrame(index=df_future_2025.index)
models_summary = {}

# --- 4 Models (Re-training) ---
print("... [1/4] Re-train Linear Regression ...")
model_lr.fit(X_train_full, Y_train_full)
pred_A_lr = model_lr.predict(X_future_A)
pred_B_lr = model_lr.predict(X_future_B)
forecast_results['LR_A'] = pred_A_lr
forecast_results['LR_B'] = pred_B_lr
models_summary['Linear Regression'] = (pred_A_lr.sum(), pred_B_lr.sum())

print("... [2/4] Re-train Random Forest ...")
model_rf.fit(X_train_full, Y_train_full)
pred_A_rf = model_rf.predict(X_future_A)
pred_B_rf = model_rf.predict(X_future_B)
forecast_results['RF_A'] = pred_A_rf
forecast_results['RF_B'] = pred_B_rf
models_summary['Random Forest'] = (pred_A_rf.sum(), pred_B_rf.sum())

print("... [3/4] Re-train XGBoost ...")
model_xgb.fit(X_train_full, Y_train_full)
pred_A_xgb = model_xgb.predict(X_future_A)
pred_B_xgb = model_xgb.predict(X_future_B)
forecast_results['XGB_A'] = pred_A_xgb
forecast_results['XGB_B'] = pred_B_xgb
models_summary['XGBoost'] = (pred_A_xgb.sum(), pred_B_xgb.sum())

print("... [4/4] Re-train LSTM ...")
scaler_X_full = MinMaxScaler()
scaler_Y_full = MinMaxScaler()
X_train_scaled_full = scaler_X_full.fit_transform(X_train_full)
Y_train_scaled_full = scaler_Y_full.fit_transform(Y_train_full.values.reshape(-1, 1))

X_train_lstm_full = X_train_scaled_full.reshape((X_train_scaled_full.shape[0], 1, X_train_scaled_full.shape[1]))

model_lstm.fit(X_train_lstm_full, Y_train_scaled_full, epochs=20, batch_size=32, verbose=0, callbacks=[early_stop])

X_future_A_scaled = scaler_X_full.transform(X_future_A)
X_future_B_scaled = scaler_X_full.transform(X_future_B)
X_future_A_lstm = X_future_A_scaled.reshape((X_future_A_scaled.shape[0], 1, X_future_A_scaled.shape[1]))
X_future_B_lstm = X_future_B_scaled.reshape((X_future_B_scaled.shape[0], 1, X_future_B_scaled.shape[1]))

pred_A_lstm_scaled = model_lstm.predict(X_future_A_lstm, verbose=0)
pred_B_lstm_scaled = model_lstm.predict(X_future_B_lstm, verbose=0)

pred_A_lstm = scaler_Y_full.inverse_transform(pred_A_lstm_scaled).flatten()
pred_B_lstm = scaler_Y_full.inverse_transform(pred_B_lstm_scaled).flatten()
forecast_results['LSTM_A'] = pred_A_lstm
forecast_results['LSTM_B'] = pred_B_lstm
models_summary['LSTM'] = (pred_A_lstm.sum(), pred_B_lstm.sum())

print("\n--- [HOÀN TẤT] Đã chạy xong 4 mô hình dự báo! ---")


# --- BƯỚC 7: TỔNG HỢP LỢI NHUẬN (Q1/2025) ---
print("\n-- [BƯỚC 7] Đang tổng hợp kết quả và tính toán Lợi nhuận Q1/2025... --")

df_summary_report = []
for model_name, (total_q_a, total_q_b) in models_summary.items():
    revenue_A = total_q_a * PRICE_PAID_A
    profit_A = total_q_a * (PRICE_PAID_A - NEW_COGS_PER_ITEM)

    revenue_B = total_q_b * PRICE_PAID_B
    profit_B = total_q_b * (PRICE_PAID_B - NEW_COGS_PER_ITEM)

    profit_change = profit_B - profit_A

    df_summary_report.append({
        "Model": model_name,
        "Total_Profit_A (Giữ giá)": profit_A,
        "Total_Profit_B (Tăng giá)": profit_B,
        "Lợi nhuận Tăng/Giảm": profit_change,
        "Total_Quantity_A": total_q_a,
        "Total_Quantity_B": total_q_b
    })

df_final_report = pd.DataFrame(df_summary_report).set_index("Model")
df_final_report = df_final_report.sort_values(by="Lợi nhuận Tăng/Giảm", ascending=False)

# Hiển thị kết quả
display(Markdown("\n" + "="*50))
display(Markdown("📊 BÁO CÁO TỔNG HỢP DỰ BÁO LỢI NHUẬN Q1/2025 (4 MÔ HÌNH)"))
display(Markdown(f"Dự báo cho {N_DAYS_FORECAST} ngày (Q1/2025) khi COGS mới là {NEW_COGS_PER_ITEM:,.0f} đ/ly."))
display(Markdown("="*50 + "\n"))

format_dict = {
    "Total_Profit_A (Giữ giá)": "{:,.0f} đ",
    "Total_Profit_B (Tăng giá)": "{:,.0f} đ",
    "Lợi nhuận Tăng/Giảm": "{:,.0f} đ",
    "Total_Quantity_A": "{:,.0f} ly",
    "Total_Quantity_B": "{:,.0f} ly"
}
display(df_final_report.style.format(format_dict).background_gradient(cmap='RdYlGn', subset=['Lợi nhuận Tăng/Giảm']))


# --- BƯỚC 8: TRỰC QUAN HÓA KẾT QUẢ DỰ BÁO (Q1/2025) ---
print("\n-- [BƯỚC 8] Đang vẽ biểu đồ dự báo (Q1/2025)... --")

best_model_name_forecast = df_final_report.index[0]
prefix_map = {'Linear': 'LR', 'Random': 'RF', 'XGBoost': 'XGB', 'LSTM': 'LSTM'}
best_model_prefix = prefix_map.get(best_model_name_forecast.split(" ")[0], 'XGB')

plt.figure(figsize=(15, 7))
forecast_results[f'{best_model_prefix}_A'].plot(label=f'Kịch bản A: Giữ giá (Lượng bán)', style='b--')
forecast_results[f'{best_model_prefix}_B'].plot(label=f'Kịch bản B: Tăng giá (Lượng bán)', style='g-')
plt.title(f'Dự báo Lượng bán Q1/2025 (Sử dụng mô hình tốt nhất: {best_model_name_forecast})')
plt.ylabel('Tổng lượng bán hàng ngày')
plt.xlabel('Ngày')
plt.legend()
plt.grid(True)
plt.savefig('forecast_comparison_chart_4_models.png')
print("Hoàn tất. Đã lưu biểu đồ vào 'forecast_comparison_chart_4_models.png'.")
plt.show()

# --- [FILE STANDALONE]: TINH CHỈNH SÂU (ADVANCED TUNING) & DỰ BÁO ---
# Giai đoạn A: Đánh giá model (R2, MAPE) VỚI TimeSeriesSplit VÀ TUNING SÂU
# Giai đoạn B: Dự báo 2 kịch bản cho Q1/2025 VỚI MODEL ĐÃ TUNING
# -----------------------------------------------------------------

# --- BƯỚC 0: IMPORT THƯ VIỆN ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import timedelta
import warnings
from IPython.display import display, Markdown

# Thư viện Preprocessing
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# [MỚI] Thư viện Tinh chỉnh
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import TimeSeriesSplit # [QUAN TRỌNG] Dùng cho chuỗi thời gian

# Thư viện 4 Mô hình
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
# Tắt cảnh báo TensorFlow
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
tf.get_logger().setLevel('ERROR')
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import EarlyStopping

# Thư viện Đánh giá
from sklearn.metrics import r2_score, mean_absolute_error, mean_absolute_percentage_error, mean_squared_error

# Cài đặt
pd.set_option('display.float_format', '{:.2f}'.format)
warnings.filterwarnings('ignore')
print("-- [BƯỚC 0] Tất cả thư viện đã được nhập thành công. --")


# --- [GIẢ ĐỊNH KỊCH BẢN] ---
# (Các giả định này dùng cho Giai đoạn B)
PRICE_INDEX_A = 0.95
PRICE_INDEX_B = 1.02
AVG_LIST_PRICE_PER_ITEM = 55000
NEW_COGS_PER_ITEM = 18000

PRICE_PAID_A = AVG_LIST_PRICE_PER_ITEM * PRICE_INDEX_A
PRICE_PAID_B = AVG_LIST_PRICE_PER_ITEM * PRICE_INDEX_B
print(f"-- [GIẢ ĐỊNH] Kịch bản A (Giữ giá): {PRICE_PAID_A:,.0f} đ / 1 ly")
print(f"-- [GIẢ ĐỊNH] Kịch bản B (Tăng giá): {PRICE_PAID_B:,.0f} đ / 1 ly")
print(f"-- [GIẢ ĐỊNH] Giá vốn mới: {NEW_COGS_PER_ITEM:,.0f} đ / 1 ly")
# ----------------------------------


# --- BƯỚC 1: TẢI VÀ TỔNG HỢP DỮ LIỆU (TẠO BẢNG HUẤN LUYỆN 2024) ---
print("\n-- [BƯỚC 1] Đang tải và tạo Bảng dữ liệu huấn luyện (2024)... --")
try:
    df_trans = pd.read_csv('transaction_data.csv')
    df_prod = pd.read_csv('product_master.csv') # Cần để lấy giá niêm yết
    df_macro = pd.read_csv('macro_context.csv')
except FileNotFoundError:
    print("LỖI: Không tìm thấy tệp CSV. Vui lòng đảm bảo 3 tệp (trans, prod, macro) nằm trong cùng thư mục.")
    # exit()

# (Thực hiện các bước chuẩn bị dữ liệu như trước)
df_trans['Date_Time'] = pd.to_datetime(df_trans['Date_Time'])
df_trans['Date'] = df_trans['Date_Time'].dt.date.astype(str)
df_macro['Date'] = pd.to_datetime(df_macro['Date']).dt.date.astype(str)

df_trans = pd.merge(
    df_trans,
    df_prod[['Product_ID', 'Unit_Price_List']],
    on='Product_ID',
    how='left'
)
df_trans = df_trans.rename(columns={'Unit_Price_Listed': 'Unit_Price_Recorded', 'Unit_Price_List': 'Unit_Price_Master'})
df_trans['Unit_Price_Master'] = df_trans['Unit_Price_Master'].fillna(df_trans['Unit_Price_Recorded'])
df_trans['Total_List_Price'] = df_trans['Quantity'] * df_trans['Unit_Price_Master']

df_daily_agg = df_trans.groupby('Date').agg(
    Total_Quantity=('Quantity', 'sum'),
    Total_Paid_Agg=('Total_Paid', 'sum'),
    Total_List_Price_Agg=('Total_List_Price', 'sum')
).reset_index()

df_daily_agg = df_daily_agg[df_daily_agg['Total_List_Price_Agg'] > 0]
df_daily_agg['Price_Index'] = df_daily_agg['Total_Paid_Agg'] / df_daily_agg['Total_List_Price_Agg']

df_train_2024_full = pd.merge(
    df_daily_agg,
    df_macro[['Date', 'Is_Weekend', 'Is_Holiday', 'Promotion_Campaign']],
    on='Date',
    how='left'
)

df_train_2024_full['Date'] = pd.to_datetime(df_train_2024_full['Date'])
df_train_2024_full = df_train_2024_full.set_index('Date')
df_train_2024_full['Month'] = df_train_2024_full.index.month
df_train_2024_full['DayOfWeek'] = df_train_2024_full.index.dayofweek

df_train_2024_full = df_train_2024_full.dropna()
print(f"Hoàn tất BƯỚC 1. Đã tạo bảng dữ liệu 2024 (full) với {len(df_train_2024_full)} ngày.")


# --- GIAI ĐOẠN A: ĐÁNH GIÁ MÔ HÌNH (VỚI TUNING SÂU) ---

print("\n\n" + "="*50)
print(" GIAI ĐOẠN A: ĐÁNH GIÁ MÔ HÌNH (R2, MAPE) VỚI TUNING SÂU")
print("="*50)

# --- BƯỚC 2: CHIA DỮ LIỆU 2024 THÀNH TẬP TRAIN VÀ TEST ---
print("\n-- [BƯỚC 2] Đang chia dữ liệu 2024 thành Train (10 tháng) và Test (2 tháng)... --")
split_date = '2024-11-01'
train_data = df_train_2024_full.loc[df_train_2024_full.index < split_date]
test_data = df_train_2024_full.loc[df_train_2024_full.index >= split_date]

target_col = 'Total_Quantity'
feature_cols = ['Price_Index', 'Is_Weekend', 'Is_Holiday', 'Promotion_Campaign', 'Month', 'DayOfWeek']

Y_train = train_data[target_col]
X_train = train_data[feature_cols]
Y_test = test_data[target_col]
X_test = test_data[feature_cols]

print(f" - Kích thước tập Train: {len(X_train)} ngày")
print(f" - Kích thước tập Test: {len(X_test)} ngày")

# --- BƯỚC 3: HUẤN LUYỆN, DỰ BÁO (TEST SET) VÀ TÍNH TOÁN CHỈ SỐ ---
print("\n-- [BƯỚC 3] Đang huấn luyện, tinh chỉnh và đánh giá 4 mô hình trên tập Test... --")

evaluation_results = []
test_predictions = pd.DataFrame(index=Y_test.index)
test_predictions['Actual'] = Y_test

# Biến để lưu các mô hình/tham số tốt nhất cho Giai đoạn B
best_model_objects = {}

# [MỚI] Định nghĩa TimeSeriesSplit để kiểm tra chéo (CV)
# Sẽ chia tập X_train (10 tháng) thành 3 phần gối đầu nhau
tscv = TimeSeriesSplit(n_splits=3)

def calculate_metrics(model_name, y_true, y_pred):
    r2 = r2_score(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    mape = mean_absolute_percentage_error(y_true, y_pred) * 100
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))

    print(f"... Hoàn tất: {model_name} (R2: {r2:.2f}, MAPE: {mape:.2f}%)")
    evaluation_results.append({
        "Model": model_name,
        "R-squared": r2,
        "MAPE (%)": mape,
        "MAE (ly)": mae,
        "RMSE (ly)": rmse
    })
    return y_pred

# --- 4 Models ---
# 1. Linear Regression
print("\n... [1/4] Đang chạy Linear Regression (Baseline) ...")
model_lr = LinearRegression()
model_lr.fit(X_train, Y_train)
pred_lr = model_lr.predict(X_test)
test_predictions['LR'] = calculate_metrics("Linear Regression", Y_test, pred_lr)
best_model_objects['LR'] = model_lr # Lưu lại model

# 2. Random Forest (VỚI TUNING SÂU HƠN)
print("\n... [2/4] Đang *TINH CHỈNH SÂU* (Tuning) Random Forest ...")
param_dist_rf = {
    'n_estimators': [100, 200, 300, 400],
    'max_depth': [None, 10, 20, 30, 40],
    'min_samples_leaf': [1, 2, 4, 6],
    'min_samples_split': [2, 5, 10],
    'max_features': ['sqrt', 'log2', 1.0] # 1.0 là tương đương "auto" cũ
}
model_rf = RandomForestRegressor(random_state=42)
random_search_rf = RandomizedSearchCV(
    estimator=model_rf,
    param_distributions=param_dist_rf,
    n_iter=30, # [MỚI] Tăng số lần thử lên 30
    cv=tscv,   # [MỚI] Dùng TimeSeriesSplit
    scoring='neg_mean_absolute_percentage_error', # Tối ưu theo MAPE
    random_state=42,
    n_jobs=-1,
    verbose=0
)
random_search_rf.fit(X_train, Y_train)
best_model_rf = random_search_rf.best_estimator_ # Đây là model RF tốt nhất
pred_rf = best_model_rf.predict(X_test)
test_predictions['RF'] = calculate_metrics("Random Forest (Tuned)", Y_test, pred_rf)
best_model_objects['RF'] = best_model_rf # Lưu lại model TỐT NHẤT

# 3. XGBoost (VỚI TUNING SÂU HƠN)
print("\n... [3/4] Đang *TINH CHỈNH SÂU* (Tuning) XGBoost ...")
param_dist_xgb = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [3, 5, 7, 9, 11],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'gamma': [0, 0.1, 0.2]
}
model_xgb = XGBRegressor(random_state=42, n_jobs=-1, objective='reg:squarederror')
random_search_xgb = RandomizedSearchCV(
    estimator=model_xgb,
    param_distributions=param_dist_xgb,
    n_iter=30, # [MỚI] Tăng số lần thử lên 30
    cv=tscv,   # [MỚI] Dùng TimeSeriesSplit
    scoring='neg_mean_absolute_percentage_error',
    random_state=42,
    n_jobs=-1,
    verbose=0
)
random_search_xgb.fit(X_train, Y_train)
best_model_xgb = random_search_xgb.best_estimator_ # Đây là model XGB tốt nhất
pred_xgb = best_model_xgb.predict(X_test)
test_predictions['XGB'] = calculate_metrics("XGBoost (Tuned)", Y_test, pred_xgb)
best_model_objects['XGB'] = best_model_xgb # Lưu lại model TỐT NHẤT

# 4. LSTM
print("\n... [4/4] Đang chạy LSTM (Baseline) ...")
scaler_X_eval = MinMaxScaler()
scaler_Y_eval = MinMaxScaler()
X_train_scaled_eval = scaler_X_eval.fit_transform(X_train)
Y_train_scaled_eval = scaler_Y_eval.fit_transform(Y_train.values.reshape(-1, 1))
X_test_scaled_eval = scaler_X_eval.transform(X_test)
X_train_lstm_eval = X_train_scaled_eval.reshape((X_train_scaled_eval.shape[0], 1, X_train_scaled_eval.shape[1]))
X_test_lstm_eval = X_test_scaled_eval.reshape((X_test_scaled_eval.shape[0], 1, X_test_scaled_eval.shape[1]))
model_lstm = Sequential()
model_lstm.add(LSTM(50, activation='relu', input_shape=(X_train_lstm_eval.shape[1], X_train_lstm_eval.shape[2])))
model_lstm.add(Dense(1))
model_lstm.compile(optimizer='adam', loss='mse')
early_stop = EarlyStopping(monitor='loss', patience=5, verbose=0)
model_lstm.fit(X_train_lstm_eval, Y_train_scaled_eval, epochs=30, batch_size=32, verbose=0, callbacks=[early_stop]) # Tăng epochs
pred_lstm_scaled = model_lstm.predict(X_test_lstm_eval, verbose=0)
pred_lstm = scaler_Y_eval.inverse_transform(pred_lstm_scaled).flatten()
test_predictions['LSTM'] = calculate_metrics("LSTM", Y_test, pred_lstm)

# --- BƯỚC 4: BÁO CÁO ĐÁNH GIÁ (R2, MAPE) ---
df_evaluation_report = pd.DataFrame(evaluation_results).set_index("Model")
df_evaluation_report = df_evaluation_report.sort_values(by="MAPE (%)", ascending=True)

display(Markdown("\n" + "="*50))
display(Markdown("📊 BÁO CÁO ĐÁNH GIÁ MÔ HÌNH (trên tập Test Nov-Dec 2024)"))
display(Markdown("="*50 + "\n"))
display(df_evaluation_report.style.format({
    "R-squared": "{:.3f}",
    "MAPE (%)": "{:.2f}%",
    "MAE (ly)": "{:,.1f}",
    "RMSE (ly)": "{:,.1f}"
}).background_gradient(cmap='RdYlGn_r', subset=['MAPE (%)']))


# --- BƯỚC 5: TRỰC QUAN HÓA KẾT QUẢ ĐÁNH GIÁ (CHI TIẾT 4 MODEL) ---
print("\n-- [BƯỚC 5] Đang trực quan hóa chi tiết 4 model (Actual vs Predicted)... --")
fig, axes = plt.subplots(4, 1, figsize=(15, 20), sharex=True)
fig.suptitle('ĐÁNH GIÁ CHI TIẾT 4 MODEL (Tập Test Nov-Dec 2024)', fontsize=16, y=1.02)
model_names = [
    ("Linear Regression", "LR"),
    ("Random Forest (Tuned)", "RF"),
    ("XGBoost (Tuned)", "XGB"),
    ("LSTM", "LSTM")
]
for i, (full_name, short_name) in enumerate(model_names):
    ax = axes[i]
    test_predictions['Actual'].plot(ax=ax, label='Sản lượng Thực tế (Actual)', style='k-', linewidth=2)
    test_predictions[short_name].plot(ax=ax, label=f'Dự báo ({full_name})', style='r--', linewidth=2)
    mape_score = df_evaluation_report.loc[full_name]["MAPE (%)"]
    ax.set_title(f'{i+1}. {full_name} (MAPE: {mape_score:.2f}%)')
    ax.set_ylabel('Tổng lượng bán hàng ngày')
    ax.legend()
    ax.grid(True)
plt.xlabel('Ngày')
plt.tight_layout()
plt.savefig('evaluation_chart_grid_4_models.png')
print("Hoàn tất. Đã lưu biểu đồ lưới vào 'evaluation_chart_grid_4_models.png'.")
plt.show()


# --- GIAI ĐOẠN B: DỰ BÁO KỊCH BẢN (CHO Q1/2025) ---

print("\n\n" + "="*50)
print(" GIAI ĐOẠN B: DỰ BÁO KỊCH BẢN (CHO Q1/2025)")
print("="*50)

# --- BƯỚC 6: HUẤN LUYỆN LẠI TRÊN TOÀN BỘ DỮ LIỆU 2024 VÀ DỰ BÁO ---
print("\n-- [BƯỚC 6] Đang huấn luyện lại 4 mô hình trên TOÀN BỘ dữ liệu 2024... --")

# Dữ liệu huấn luyện (full)
Y_train_full = df_train_2024_full[target_col]
X_train_full = df_train_2024_full[feature_cols]

# Dữ liệu tương lai (Q1/2025)
df_future_2025 = pd.DataFrame(index=pd.date_range(start='2025-01-01', periods=90, freq='D'))
df_future_2025['Is_Weekend'] = (df_future_2025.index.dayofweek >= 5).astype(int)
df_future_2025['Month'] = df_future_2025.index.month
df_future_2025['DayOfWeek'] = df_future_2025.index.dayofweek
df_future_2025['Is_Holiday'] = 0
df_future_2025['Promotion_Campaign'] = 0

# Tạo 2 kịch bản X_future
X_future_A = df_future_2025.copy()
X_future_A['Price_Index'] = PRICE_INDEX_A
X_future_A = X_future_A[feature_cols]
X_future_B = df_future_2025.copy()
X_future_B['Price_Index'] = PRICE_INDEX_B
X_future_B = X_future_B[feature_cols]

# Lưu trữ kết quả
forecast_results = pd.DataFrame(index=df_future_2025.index)
models_summary = {}

# --- 4 Models (Re-training với model/tham số tốt nhất) ---
print("... [1/4] Re-train Linear Regression ...")
model_lr_final = LinearRegression()
model_lr_final.fit(X_train_full, Y_train_full)
pred_A_lr = model_lr_final.predict(X_future_A)
pred_B_lr = model_lr_final.predict(X_future_B)
forecast_results['LR_A'] = pred_A_lr
forecast_results['LR_B'] = pred_B_lr
models_summary['Linear Regression'] = (pred_A_lr.sum(), pred_B_lr.sum())

print("... [2/4] Re-train Random Forest (với tham số Tốt nhất)...")
# Tạo model RF mới với tham số tốt nhất từ Giai đoạn A và fit trên 100% data
best_params_rf = random_search_rf.best_params_
model_rf_final = RandomForestRegressor(random_state=42, n_jobs=-1, **best_params_rf)
model_rf_final.fit(X_train_full, Y_train_full) # Fit trên 100% data
pred_A_rf = model_rf_final.predict(X_future_A)
pred_B_rf = model_rf_final.predict(X_future_B)
forecast_results['RF_A'] = pred_A_rf
forecast_results['RF_B'] = pred_B_rf
models_summary['Random Forest (Tuned)'] = (pred_A_rf.sum(), pred_B_rf.sum())

print("... [3/4] Re-train XGBoost (với tham số Tốt nhất)...")
# Tạo model XGB mới với tham số tốt nhất và fit trên 100% data
best_params_xgb = random_search_xgb.best_params_
model_xgb_final = XGBRegressor(random_state=42, n_jobs=-1, objective='reg:squarederror', **best_params_xgb)
model_xgb_final.fit(X_train_full, Y_train_full) # Fit trên 100% data
pred_A_xgb = model_xgb_final.predict(X_future_A)
pred_B_xgb = model_xgb_final.predict(X_future_B)
forecast_results['XGB_A'] = pred_A_xgb
forecast_results['XGB_B'] = pred_B_xgb
models_summary['XGBoost (Tuned)'] = (pred_A_xgb.sum(), pred_B_xgb.sum())

print("... [4/4] Re-train LSTM ...")
# LSTM cũng được fit lại trên 100% data
scaler_X_full = MinMaxScaler()
scaler_Y_full = MinMaxScaler()
X_train_scaled_full = scaler_X_full.fit_transform(X_train_full)
Y_train_scaled_full = scaler_Y_full.fit_transform(Y_train_full.values.reshape(-1, 1))
X_train_lstm_full = X_train_scaled_full.reshape((X_train_scaled_full.shape[0], 1, X_train_scaled_full.shape[1]))
# Tạo model LSTM mới
model_lstm_final = Sequential()
model_lstm_final.add(LSTM(50, activation='relu', input_shape=(X_train_lstm_full.shape[1], X_train_lstm_full.shape[2])))
model_lstm_final.add(Dense(1))
model_lstm_final.compile(optimizer='adam', loss='mse')
model_lstm_final.fit(X_train_lstm_full, Y_train_scaled_full, epochs=30, batch_size=32, verbose=0, callbacks=[early_stop]) # Tăng epochs

X_future_A_scaled = scaler_X_full.transform(X_future_A)
X_future_B_scaled = scaler_X_full.transform(X_future_B)
X_future_A_lstm = X_future_A_scaled.reshape((X_future_A_scaled.shape[0], 1, X_future_A_scaled.shape[1]))
X_future_B_lstm = X_future_B_scaled.reshape((X_future_B_scaled.shape[0], 1, X_future_B_scaled.shape[1]))
pred_A_lstm_scaled = model_lstm_final.predict(X_future_A_lstm, verbose=0)
pred_B_lstm_scaled = model_lstm_final.predict(X_future_B_lstm, verbose=0)
pred_A_lstm = scaler_Y_full.inverse_transform(pred_A_lstm_scaled).flatten()
pred_B_lstm = scaler_Y_full.inverse_transform(pred_B_lstm_scaled).flatten()
forecast_results['LSTM_A'] = pred_A_lstm
forecast_results['LSTM_B'] = pred_B_lstm
models_summary['LSTM'] = (pred_A_lstm.sum(), pred_B_lstm.sum())

print("\n--- [HOÀN TẤT] Đã chạy xong 4 mô hình dự báo! ---")


# --- BƯỚC 7: TỔNG HỢP LỢI NHUẬN (Q1/2025) ---
print("\n-- [BƯỚC 7] Đang tổng hợp kết quả và tính toán Lợi nhuận Q1/2025... --")

df_summary_report = []
for model_name, (total_q_a, total_q_b) in models_summary.items():
    revenue_A = total_q_a * PRICE_PAID_A
    profit_A = total_q_a * (PRICE_PAID_A - NEW_COGS_PER_ITEM)

    revenue_B = total_q_b * PRICE_PAID_B
    profit_B = total_q_b * (PRICE_PAID_B - NEW_COGS_PER_ITEM)

    profit_change = profit_B - profit_A

    df_summary_report.append({
        "Model": model_name,
        "Total_Profit_A (Giữ giá)": profit_A,
        "Total_Profit_B (Tăng giá)": profit_B,
        "Lợi nhuận Tăng/Giảm": profit_change,
        "Total_Quantity_A": total_q_a,
        "Total_Quantity_B": total_q_b
    })

df_final_report = pd.DataFrame(df_summary_report).set_index("Model")
df_final_report = df_final_report.sort_values(by="Lợi nhuận Tăng/Giảm", ascending=False)

# Hiển thị kết quả
display(Markdown("\n" + "="*50))
display(Markdown("📊 BÁO CÁO TỔNG HỢP DỰ BÁO LỢI NHUẬN Q1/2025 (4 MÔ HÌNH)"))
display(Markdown(f"Dự báo cho {N_DAYS_FORECAST} ngày (Q1/2025) khi COGS mới là {NEW_COGS_PER_ITEM:,.0f} đ/ly."))
display(Markdown("="*50 + "\n"))

format_dict = {
    "Total_Profit_A (Giữ giá)": "{:,.0f} đ",
    "Total_Profit_B (Tăng giá)": "{:,.0f} đ",
    "Lợi nhuận Tăng/Giảm": "{:,.0f} đ",
    "Total_Quantity_A": "{:,.0f} ly",
    "Total_Quantity_B": "{:,.0f} ly"
}
display(df_final_report.style.format(format_dict).background_gradient(cmap='RdYlGn', subset=['Lợi nhuận Tăng/Giảm']))


# --- BƯỚC 8: TRỰC QUAN HÓA KẾT QUẢ DỰ BÁO (Q1/2025) ---
print("\n-- [BƯỚC 8] Đang vẽ biểu đồ dự báo (Q1/2025)... --")

best_model_name_forecast = df_final_report.index[0] # Lấy model có lợi nhuận tăng/giảm tốt nhất
prefix_map = {'Linear': 'LR', 'Random': 'RF', 'XGBoost': 'XGB', 'LSTM': 'LSTM'}
best_model_prefix = prefix_map.get(best_model_name_forecast.split(" ")[0], 'XGB')

plt.figure(figsize=(15, 7))
forecast_results[f'{best_model_prefix}_A'].plot(label=f'Kịch bản A: Giữ giá (Lượng bán)', style='b--')
forecast_results[f'{best_model_prefix}_B'].plot(label=f'Kịch bản B: Tăng giá (Lượng bán)', style='g-')
plt.title(f'Dự báo Lượng bán Q1/2025 (Sử dụng mô hình tốt nhất: {best_model_name_forecast})')
plt.ylabel('Tổng lượng bán hàng ngày')
plt.xlabel('Ngày')
plt.legend()
plt.grid(True)
plt.savefig('forecast_comparison_chart_4_models.png')
print("Hoàn tất. Đã lưu biểu đồ vào 'forecast_comparison_chart_4_models.png'.")
plt.show()