# -*- coding: utf-8 -*-
"""EDA_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_OgI8yXP1_NycBDTPKiMh8Ujvj0TApK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker

# ==============================
# 0. CONFIG
# ==============================

CURRENT_YEAR = 2024  # dùng để tính Age từ YoB

# ==============================
# 1. LOAD RAW DATA
# ==============================

def load_raw_data(data_dir="."):
    df_customer = pd.read_csv(f"{data_dir}/customer_profile.csv")
    df_trans    = pd.read_csv(f"{data_dir}/transaction_data.csv")
    df_product  = pd.read_csv(f"{data_dir}/product_master.csv")
    df_macro    = pd.read_csv(f"{data_dir}/macro_context.csv")
    return df_customer, df_trans, df_product, df_macro


# ==============================
# 2. PREPROCESS – CUSTOMER PROFILE
# ==============================

def preprocess_customer(df_customer, current_year=CURRENT_YEAR):
    df = df_customer.copy()

    # Chuẩn hóa tên cột: "Income level" -> "Income_Level"
    df = df.rename(columns={"Income level": "Income_Level"})

    # Strip khoảng trắng, chuẩn text
    text_cols = ["Occupation", "Income_Level", "Gender", "Membership_Tier"]
    for col in text_cols:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip()

    # Tính Age từ YoB (Year of Birth)
    if "YoB" in df.columns:
        df["Age"] = current_year - df["YoB"]
        # vì YoB đang là float, ta convert Age sang int nhưng giữ NA nếu thiếu
        df["Age"] = df["Age"].round().astype("Int64")

        # Nhóm tuổi
        df["Age_Group"] = pd.cut(
            df["Age"].astype("float"),
            bins=[0, 18, 25, 35, 45, 60, 120],
            labels=["<=18", "19-25", "26-35", "36-45", "46-60", "60+"],
            right=True
        )
    else:
        df["Age_Group"] = pd.NA

    # Ép kiểu category cho các field phân loại
    cat_cols = ["Occupation", "Income_Level", "Gender", "Membership_Tier", "Age_Group"]
    for c in cat_cols:
        if c in df.columns:
            df[c] = df[c].astype("category")

    # Ép Customer_ID về category (để merge với transaction)
    if "Customer_ID" in df.columns:
        df["Customer_ID"] = df["Customer_ID"].astype("category")

    return df


# ==============================
# 3. PREPROCESS – PRODUCT MASTER
# ==============================

def preprocess_product(df_product):
    df = df_product.copy()

    # Clean text cơ bản
    text_cols = ["Product_Name", "Category", "Size"]
    for col in text_cols:
        if col in df.columns:
            df[col] = (
                df[col]
                .astype(str)
                .str.strip()
                .replace("nan", np.nan)
            )

    # Fill Unknown cho các cột phân loại (chỉ những cột tồn tại)
    existing_cat_cols = [c for c in ["Category", "Size"] if c in df.columns]
    if existing_cat_cols:
        df[existing_cat_cols] = df[existing_cat_cols].fillna("Unknown")

    # Tính margin trên đơn vị sản phẩm
    if set(["Unit_Price_List", "COGS"]).issubset(df.columns):
        df["Unit_Margin"] = df["Unit_Price_List"] - df["COGS"]
        df["Margin_Rate"] = np.where(
            df["Unit_Price_List"] > 0,
            df["Unit_Margin"] / df["Unit_Price_List"],
            np.nan
        )
    else:
        df["Unit_Margin"] = np.nan
        df["Margin_Rate"] = np.nan

    # ID sang category
    if "Product_ID" in df.columns:
        df["Product_ID"] = df["Product_ID"].astype("category")

    # Category fields -> category dtype
    cat_cols = ["Product_Name", "Category", "Size"]
    for c in cat_cols:
        if c in df.columns:
            df[c] = df[c].astype("category")

    return df


# ==============================
# 4. PREPROCESS – TRANSACTION DATA
# ==============================

def preprocess_transaction(df_trans):
    df = df_trans.copy()

    # 4.1. Chuẩn hóa datetime
    df["Date_Time"] = pd.to_datetime(df["Date_Time"], errors="coerce")
    df = df.dropna(subset=["Date_Time"]).copy()

    # 4.2. Feature thời gian
    df["Date"]       = df["Date_Time"].dt.date
    df["Year"]       = df["Date_Time"].dt.year
    df["Month"]      = df["Date_Time"].dt.month
    df["Day"]        = df["Date_Time"].dt.day
    df["Hour"]       = df["Date_Time"].dt.hour
    df["DayOfWeek"]  = df["Date_Time"].dt.dayofweek  # 0=Mon, 6=Sun
    df["Is_Weekend_Trans"] = df["DayOfWeek"].isin([5, 6]).astype(int)

    # 4.3. Feature doanh thu & giá
    df["Gross_Revenue"] = df["Quantity"] * df["Unit_Price_Listed"]

    df["Discount_Rate"] = np.where(
        df["Gross_Revenue"] > 0,
        df["Discount_Amount"] / df["Gross_Revenue"],
        0
    )

    df["Effective_Unit_Price"] = np.where(
        df["Quantity"] > 0,
        df["Total_Paid"] / df["Quantity"],
        np.nan
    )

    # 4.4. Ép kiểu category cho các ID
    for c in ["Transaction_ID", "Customer_ID", "Product_ID", "Store_ID"]:
        if c in df.columns:
            df[c] = df[c].astype("category")

    return df


# ==============================
# 5. PREPROCESS – MACRO CONTEXT
# ==============================

def preprocess_macro(df_macro):
    df = df_macro.copy()

    # Date -> datetime.date
    df["Date"] = pd.to_datetime(df["Date"], errors="coerce").dt.date

    # Đảm bảo các flag là int
    for col in ["Is_Weekend", "Is_Holiday", "Promotion_Campaign"]:
        if col in df.columns:
            df[col] = df[col].astype(int)

    # Đổi tên một số cột cho rõ nghĩa, tránh đụng tên với transaction
    rename_map = {
        "Is_Weekend": "Is_Weekend_Macro",
        "Is_Holiday": "Is_Holiday_Flag",
        "Promotion_Campaign": "Promotion_Campaign_Flag",
        "Monthly_Index": "Macro_Monthly_Index"
    }
    df = df.rename(columns=rename_map)

    # Bỏ cột Month vì đã encode trong Date / Year / Month từ transaction
    if "Month" in df.columns:
        df = df.drop(columns=["Month"])

    return df


# ==============================
# 6. BUILD MASTER TABLE
# ==============================

def build_master_table(df_trans_clean, df_product_clean, df_customer_clean, df_macro_clean):
    """
    Merge lần lượt:
    transaction + product
    -> + customer
    -> + macro (theo Date)
    """
    # 6.1. transaction + product
    df_master = df_trans_clean.merge(
        df_product_clean,
        on="Product_ID",
        how="left",
        validate="many_to_one"  # nhiều giao dịch - 1 sản phẩm
    )

    # 6.2. + customer
    df_master = df_master.merge(
        df_customer_clean,
        on="Customer_ID",
        how="left",
        validate="many_to_one"  # nhiều giao dịch - 1 khách hàng
    )

    # 6.3. + macro theo Date
    df_master = df_master.merge(
        df_macro_clean,
        on="Date",
        how="left"
    )

    # Sắp xếp theo thời gian
    df_master = df_master.sort_values("Date_Time").reset_index(drop=True)

    return df_master


# ==============================
# 7. RUN ALL – TIỀN XỬ LÍ FULL PIPELINE
# ==============================

def run_full_pipeline(data_dir=".", current_year=CURRENT_YEAR, verbose=True):
    # 1. Load
    df_customer_raw, df_trans_raw, df_product_raw, df_macro_raw = load_raw_data(data_dir)

    # 2. Preprocess từng bảng
    df_customer_clean = preprocess_customer(df_customer_raw, current_year=current_year)
    df_product_clean  = preprocess_product(df_product_raw)
    df_trans_clean    = preprocess_transaction(df_trans_raw)
    df_macro_clean    = preprocess_macro(df_macro_raw)

    # 3. Build df_master
    df_master = build_master_table(
        df_trans_clean,
        df_product_clean,
        df_customer_clean,
        df_macro_clean
    )

    if verbose:
        print("=== SHAPES ===")
        print("df_customer_clean:", df_customer_clean.shape)
        print("df_product_clean :", df_product_clean.shape)
        print("df_trans_clean   :", df_trans_clean.shape)
        print("df_macro_clean   :", df_macro_clean.shape)
        print("df_master        :", df_master.shape)
        print("\n=== df_master HEAD ===")
        print(df_master.head())
        print("\n=== df_master INFO ===")
        print(df_master.info())

    return {
        "df_customer": df_customer_clean,
        "df_product": df_product_clean,
        "df_trans": df_trans_clean,
        "df_macro": df_macro_clean,
        "df_master": df_master,
    }


# ==============================
# 8. EXAMPLE USAGE
# ==============================

if __name__ == "__main__":
    # Nếu file CSV ở cùng thư mục thì để data_dir="."
    dfs = run_full_pipeline(data_dir=".")
    df_master = dfs["df_master"]

cols_to_drop = [
    "Gross_Revenue",
    "Discount_Rate",
    "Effective_Unit_Price",
    "Unit_Margin",
    "Margin_Rate",
    "product_specific_mult",
    "Macro_Monthly_Index"
]

master_df = df_master.drop(
    columns=[c for c in cols_to_drop if c in df_master.columns]
).copy()

print("Số cột ban đầu:", df_master.shape[1])
print("Số cột sau khi drop:", df_master_reduced.shape[1])
print("Các cột đã drop:", [c for c in cols_to_drop if c in df_master.columns])

master_df['Month'] = master_df['Month'].astype(int)
df_customers_monthly = (
    df_master
      .groupby("Month")["Customer_ID"]
      .nunique()
      .reindex(range(1, 13), fill_value=0)  # ép đủ 12 tháng
      .reset_index()
)
df_customers_monthly.columns = ["Month", "Unique_Customers"]
print(df_customers_monthly)

master_df.info()

master_df.isnull().sum().sort_values(ascending=False)

master_df.describe().T

categorical_cols = master_df.select_dtypes(include=["category", "object"]).columns.tolist()
print("Categorical columns:", categorical_cols)

"""#Đơn biến

###Customer demographic
"""

sns.set(style="whitegrid")

# Bảng màu pastel dùng chung (giống chart Income)
soft_palette = sns.color_palette("pastel", 6)

fig, axes = plt.subplots(2, 3, figsize=(20, 10))
fig.suptitle("Customer Profile Overview", fontsize=16, fontweight="bold")

# -------------------------
# 1. Age distribution (Histogram)
# -------------------------
ax1 = axes[0, 0]
sns.histplot(df_master["Age"], kde=True, bins=25, ax=ax1, color=soft_palette[0])
ax1.set_title("Customer Age Distribution")
ax1.set_xlabel("Age")
ax1.set_ylabel("Count")

# -------------------------
# 2. Occupation (Bar)
# -------------------------
ax2 = axes[0, 1]
if "Occupation" in df_master.columns:
    occ_counts = df_master["Occupation"].value_counts().head(10)
    occ_counts.plot(kind="bar", ax=ax2, color=soft_palette[1])
    ax2.set_title("Top 10 Occupations")
    ax2.set_xlabel("Occupation")
    ax2.set_ylabel("Count")
    ax2.tick_params(axis="x", rotation=30)
else:
    ax2.text(0.5, 0.5, "Occupation not found", ha="center", va="center")
    ax2.axis("off")

# -------------------------
# 3. Income Level (Bar) – cùng palette với chart bạn gửi
# -------------------------
ax3 = axes[0, 2]
if "Income_Level" in df_master.columns:
    income_counts = df_master["Income_Level"].value_counts().reindex([
        "< 2M", "2-5M", "5-10M", "10-20M", "20-50M", "> 50M"
    ]).dropna()
    income_counts.plot(
        kind="barh",
        ax=ax3,
        color=soft_palette[:len(income_counts)]
    )
    ax3.set_title("Income Level Distribution")
    ax3.set_xlabel("Số lượng Khách hàng")
    ax3.set_ylabel("Income Level")
else:
    ax3.text(0.5, 0.5, "Income level not found", ha="center", va="center")
    ax3.axis("off")

# -------------------------
# COMMON STYLE cho 3 PIE CHART (dùng soft_palette)
# -------------------------
common_pie_kwargs = dict(
    autopct="%1.1f%%",
    startangle=90,
    counterclock=False,
    wedgeprops={"edgecolor": "white"},
    textprops={"fontsize": 10}
)

# -------------------------
# 4. Age Group (Pie Chart)
# -------------------------
ax4 = axes[1, 0]
if "Age_Group" in df_master.columns:
    age_grp_counts = df_master["Age_Group"].value_counts()
    ax4.pie(
        age_grp_counts.values,
        labels=age_grp_counts.index,
        colors=soft_palette[:len(age_grp_counts)],
        **common_pie_kwargs
    )
    ax4.set_title("Age Group Distribution")
    ax4.axis("equal")
else:
    ax4.text(0.5, 0.5, "Age_Group not found", ha="center", va="center")
    ax4.axis("off")

# -------------------------
# 5. Gender (Pie Chart)
# -------------------------
ax5 = axes[1, 1]
if "Gender" in df_master.columns:
    gender_counts = df_master["Gender"].value_counts()
    ax5.pie(
        gender_counts.values,
        labels=gender_counts.index,
        colors=soft_palette[:len(gender_counts)],
        **common_pie_kwargs
    )
    ax5.set_title("Gender Distribution")
    ax5.axis("equal")
else:
    ax5.text(0.5, 0.5, "Gender not found", ha="center", va="center")
    ax5.axis("off")

# -------------------------
# 6. Membership Tier (Pie Chart)
# -------------------------
ax6 = axes[1, 2]
if "Membership_Tier" in df_master.columns:
    tier_counts = df_master["Membership_Tier"].value_counts()
    ax6.pie(
        tier_counts.values,
        labels=tier_counts.index,
        colors=soft_palette[:len(tier_counts)],
        **common_pie_kwargs
    )
    ax6.set_title("Membership Tier Distribution")
    ax6.axis("equal")
else:
    ax6.text(0.5, 0.5, "Membership_Tier not found", ha="center", va="center")
    ax6.axis("off")

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""* **Nhóm tuổi trọng tâm**: Khách hàng tập trung mạnh nhất ở độ tuổi 19 đến 35 tuổi (chiếm 77.6%), cho thấy đây là một cơ sở khách hàng trẻ và năng động.

* **Giới tính & Nghề nghiệp**: Khách hàng Nữ (60.2%) chiếm ưu thế và nghề nghiệp phổ biến nhất là Nhân viên Văn phòng, tiếp theo là Sinh viên và Freelancer.

* **Thu nhập & Mức độ gắn bó**: Thu nhập tập trung ở mức 20-50M (triệu), cho thấy khả năng chi trả khá. Tuy nhiên, hơn một nửa khách hàng đang ở hạng thành viên Standard (53.8%), cho thấy mức độ gắn bó trung thành còn ở mức cơ bản.

###Product performance
"""

# Làm việc trên bản copy cho an toàn
df = df_master_reduced.copy()

# Đảm bảo có cột Category
if "Category" not in df.columns:
    raise ValueError("DataFrame không có cột 'Category'")

# ==========================
# 1. Danh sách Category
# ==========================
unique_categories = df["Category"].unique()
print("Các Category hiện có trong dataset:")
for c in unique_categories:
    print(" -", c)

# ==========================
# 2. Tóm tắt theo Category
# ==========================
cat_summary = (
    df.groupby("Category")
      .agg(
          Total_Transactions=("Transaction_ID", "nunique"),
          Total_Quantity=("Quantity", "sum"),
          Total_Revenue=("Total_Paid", "sum"),
          Num_SKU=("Product_ID", "nunique")
      )
      .reset_index()
      .sort_values("Total_Revenue", ascending=False)
)

print("\n=== TÓM TẮT CATEGORY (sắp theo Doanh thu) ===")
print(cat_summary)

# ==========================
# 3. Danh sách tên sản phẩm
# ==========================
print("\n=== DANH SÁCH TÊN SẢN PHẨM HIỆN CÓ ===")
unique_products = (
    df["Product_Name"]
    .dropna()
    .astype(str)
    .str.strip()
    .sort_values()
    .unique()
)
for p in unique_products:
    print(" -", p)

# ==========================
# 4. Danh sách Size hiện có
# ==========================
print("\n=== DANH SÁCH SIZE HIỆN CÓ ===")
unique_sizes = (
    df["Size"]
    .dropna()
    .astype(str)
    .str.strip()
    .sort_values()
    .unique()
)
for s in unique_sizes:
    print(" -", s)

# ==========================
# 5. Bảng Product_Name x Size (không trùng)
# ==========================
print("\n=== BẢNG SẢN PHẨM THEO SIZE (UNIQUE) ===")
product_size_table = (
    df[["Product_ID", "Product_Name", "Category", "Size"]]
    .drop_duplicates()
    .sort_values(["Category", "Product_Name", "Size"])
)

print(product_size_table.head(50))  # in thử 50 dòng đầu, cần thì bỏ head()

# ======================================
# 0. COPY DATAFRAME & CHUẨN HÓA NGÀY
# ======================================
df = df_master_reduced.copy()

# Đảm bảo Date là datetime (hiện đang là object)
df["Date"] = pd.to_datetime(df["Date"])

# Thêm YearMonth cho phân tích theo tháng
df["YearMonth"] = df["Date"].dt.to_period("M").astype(str)

sns.set(style="whitegrid")

# ======================================
# 1. KPI TỔNG QUAN
# ======================================

total_revenue   = df["Total_Paid"].sum()
total_orders    = df["Transaction_ID"].nunique()
total_customers = df["Customer_ID"].nunique()
total_items     = df["Quantity"].sum()

aov             = total_revenue / total_orders             # Average Order Value
items_per_order = total_items / total_orders               # Số món / đơn
rev_per_customer = total_revenue / total_customers         # Doanh thu / khách

print("===== TỔNG QUAN KINH DOANH HIGHLANDS =====")
print(f"Tổng doanh thu       : {total_revenue:,.0f} VND")
print(f"Số đơn hàng          : {total_orders:,}")
print(f"Số khách hàng        : {total_customers:,}")
print(f"Tổng số sản phẩm bán : {total_items:,}")
print(f"AOV (Doanh thu/đơn)  : {aov:,.0f} VND")
print(f"Số món / đơn         : {items_per_order:,.2f}")
print(f"Doanh thu / khách    : {rev_per_customer:,.0f} VND")

# ======================================
# 4. DOANH THU THEO CỬA HÀNG (STORE)
# ======================================

rev_by_store = (
    df.groupby("Store_ID")["Total_Paid"]
      .sum()
      .sort_values(ascending=False)
      .reset_index()
)

top_n = 10
top_store = rev_by_store.head(top_n)

# --- Bước 4: Vẽ biểu đồ (ĐÃ SỬA) ---
plt.figure(figsize=(12, 7)) # Tăng kích thước (rộng 12, cao 7)

# Sử dụng biểu đồ ngang (horizontal bar plot)
# Trục Y là Tên cửa hàng (plot_col), Trục X là Doanh thu
# Seaborn sẽ tự động sắp xếp đúng thứ tự (đã sort)
ax = sns.barplot(
    data=top_store,
    x="Total_Paid",
    y="Store_ID", # Fixed: Changed plot_col to "Store_ID"
    palette="viridis" # Thêm bảng màu
)

plt.title(f"Top {top_n} cửa hàng theo doanh thu", fontsize=16, fontweight='bold')
plt.xlabel("Doanh thu (VND)", fontsize=12)
plt.ylabel("Cửa hàng", fontsize=12)

# Thêm định dạng cho trục X (ví dụ: 30B, 20B cho Tỷ)
ax.xaxis.set_major_formatter(
    ticker.FuncFormatter(lambda x, pos: f'{x/1e9:.1f}B')
)

plt.tight_layout()
plt.show()

"""* Các cửa hàng HL-HCM (khu vực Hoàn Kiếm) và HL-CC (khu vực Ba Đình) là hai cửa hàng dẫn đầu về doanh thu, với mức $\approx 13.8$ Tỷ VND và $\approx 12.9$ Tỷ VND bởi nằm ở trung tâm hành chính, thương mại, và du lịch của thành phố.
* Các cửa hàng HL-Aeon và HL-Times (khu đô thị lớn/TTTM) mang lại doanh thu rất cao và ổn định, đạt trên 10 Tỷ VND. Vị trí này khai thác hiệu quả lượng khách hàng sinh sống, giải trí, và mua sắm vào các khung giờ ngoài hành chính.
* Các cửa hàng HL-CB (gần khu vực Đống Đa) và HL-BK (gần khu vực Bách Khoa) có doanh thu ở mức trung bình khá (khoảng $8.8$ - $9.6$ Tỷ VND). Dù nằm gần các khu trường học và khu dân cư trẻ, doanh thu đạt mức trung bình khá, có thể do giá trị đơn hàng trung bình thấp hơn.
* Các cửa hàng HL-DT, HL-K, và HL-TH (nằm trong/gần các khu tập trung tòa nhà văn phòng) nằm ở nhóm dưới của Top 10 (từ $\approx 7.0$ Tỷ VND đến $\approx 8.4$ Tỷ VND). Điều này cho thấy sự cạnh tranh cao hoặc khó khăn trong việc tối ưu hóa giao dịch nhanh vào giờ cao điểm tại các khu vực làm việc này.
"""

print("Calculating Gross Profit (Margin) for each transaction...")
df_master['Transaction_Margin'] = (df_master['Unit_Price_List'] - df_master['COGS']) * df_master['Quantity']
print("...Column 'Transaction_Margin' created successfully.")


# 2. Revenue & Profit per Day
daily_kpis = (
    df_master.groupby("Date")
    .agg(
        Daily_Revenue=("Total_Paid", "sum"),
        Daily_Profit=("Transaction_Margin", "sum")
    )
    .reset_index()
)
print(daily_kpis.head())


# 3. Attach DayOfWeek + Weekend flag
daily_kpis = daily_kpis.merge(
    df_master[["Date", "DayOfWeek", "Is_Weekend_Macro"]].drop_duplicates(),
    on="Date",
    how="left"
)


# 4. Average Revenue: Weekday vs Weekend
avg_rev_weekend = (
    daily_kpis.groupby("Is_Weekend_Macro")["Daily_Revenue"]
    .mean()
    .reset_index()
)
avg_rev_weekend["Is_Weekend_Macro"] = avg_rev_weekend["Is_Weekend_Macro"].map({
    0: "Weekday",
    1: "Weekend"
})

print("\nAverage Daily Revenue (Weekday vs Weekend):")
print(avg_rev_weekend)


# 5. Average Profit: Weekday vs Weekend
avg_profit_weekend = (
    daily_kpis.groupby("Is_Weekend_Macro")["Daily_Profit"]
    .mean()
    .reset_index()
)
avg_profit_weekend["Is_Weekend_Macro"] = avg_profit_weekend["Is_Weekend_Macro"].map({
    0: "Weekday",
    1: "Weekend"
})

print("\nAverage Daily Profit (Weekday vs Weekend):")
print(avg_profit_weekend)


# 6. Attach Holiday + Promotion flags
daily_kpis = daily_kpis.merge(
    df_master[["Date", "Is_Holiday_Flag"]].drop_duplicates(),
    on="Date",
    how="left"
)

daily_kpis = daily_kpis.merge(
    df_master[["Date", "Promotion_Campaign_Flag"]].drop_duplicates(),
    on="Date",
    how="left"
)


# Average Revenue: Promo vs Non-Promo
avg_rev_promo = (
    daily_kpis.groupby("Promotion_Campaign_Flag")["Daily_Revenue"]
    .mean()
    .reset_index()
)
avg_rev_promo["Promotion_Campaign_Flag"] = avg_rev_promo["Promotion_Campaign_Flag"].map({
    0: "Regular Day",
    1: "Promo Day"
})

print("\nAverage Daily Revenue (Regular Day vs Promo Day):")
print(avg_rev_promo)


# Average Profit: Promo vs Non-Promo
avg_profit_promo = (
    daily_kpis.groupby("Promotion_Campaign_Flag")["Daily_Profit"]
    .mean()
    .reset_index()
)
avg_profit_promo["Promotion_Campaign_Flag"] = avg_profit_promo["Promotion_Campaign_Flag"].map({
    0: "Regular Day",
    1: "Promo Day"
})

print("\nAverage Daily Profit (Regular Day vs Promo Day):")
print(avg_profit_promo)

#========================================================
# 2. PHÂN TÍCH SẢN PHẨM (PRODUCT MASTER)
# ========================================================

if df_product is not None:
    print("\n--- Bắt đầu Phân tích Sản phẩm (Product Master) ---")

    # 2.1. Feature Engineering (Kỹ thuật Đặc trưng)

    # [THÊM LẠI] Tính Gross_Margin_Per_Unit (Cần cho tính Lợi nhuận)
    df_product['Gross_Margin_Per_Unit'] = df_product['Unit_Price_List'] - df_product['COGS']

    # (Code gốc của bạn)
    df_product['Gross_Margin_Rate'] = (df_product['Gross_Margin_Per_Unit'] / df_product['Unit_Price_List']).fillna(0)
    print("Đã tạo cột 'Gross_Margin_Per_Unit' và 'Gross_Margin_Rate'.")

    # 2.2. Phân tích Đơn biến (Categorical)
    print("\n[2.2] Phân tích Đơn biến (Biến Phân loại):")



    # Kiểm tra xem df_trans (biến chứa data giao dịch) có tồn tại không
    if 'df_trans' in locals() and df_trans is not None:
        print("\n[BỔ SUNG] Tính toán Tổng Doanh thu và Lợi nhuận từ df_trans...")

        # 1. Gộp df_trans với df_product để lấy Category và Margin
        df_merged_perf = pd.merge(
            df_trans[['Product_ID', 'Quantity', 'Total_Paid']],
            df_product[['Product_ID', 'Category', 'Gross_Margin_Per_Unit']],
            on='Product_ID',
            how='left'
        )

        # 2. Tính Lợi nhuận gộp cho từng dòng giao dịch
        df_merged_perf['Transaction_Profit'] = df_merged_perf['Gross_Margin_Per_Unit'] * df_merged_perf['Quantity']

        # 3. Gộp (Group by) theo Category và Tính tổng
        df_perf_category = df_merged_perf.groupby('Category').agg(
            Total_Revenue=('Total_Paid', 'sum'),
            Total_Profit=('Transaction_Profit', 'sum')
        ).reset_index()

        print("Tổng hợp Doanh thu & Lợi nhuận theo Category:")
        print(df_perf_category.to_markdown(index=False, floatfmt=",.0f"))

        # 4. Vẽ 2 biểu đồ Pie chart
        plt.figure(figsize=(14, 7))

        # Biểu đồ 1: Tỷ trọng DOANH THU
        plt.subplot(1, 2, 1)
        plt.pie(
            df_perf_category['Total_Revenue'],
            labels=df_perf_category['Category'],
            autopct='%1.1f%%',  # Hiển thị %
            startangle=90,      # Bắt đầu từ 90 độ
            colors=sns.color_palette("pastel")
        )
        plt.title('Revenue Share by Category', fontsize=14)

        # Biểu đồ 2: Tỷ trọng LỢI NHUẬN
        plt.subplot(1, 2, 2)
        plt.pie(
            df_perf_category['Total_Profit'],
            labels=df_perf_category['Category'],
            autopct='%1.1f%%',
            startangle=90,
            colors=sns.color_palette("pastel")
        )
        plt.title('Gross Profit Share by Category', fontsize=14)

        plt.tight_layout()
        plt.savefig("product_pie_charts_revenue_profit.png")
        print("Đã lưu biểu đồ: 'product_pie_charts_revenue_profit.png'")

    else:
        print("\n[CẢNH BÁO] Không tìm thấy biến 'df_trans'. Bỏ qua phần vẽ pie chart (Cần dữ liệu giao dịch).")

    # Biểu đồ 3: Biên lợi nhuận (VND)
    plt.figure(figsize=(12, 8))
    sns.boxplot(data=df_product, x='Category', y='Gross_Margin_Per_Unit')
    plt.title('Distribution of Gross Margin per Unit (VND) by Category', fontsize=16, fontweight='bold')
    plt.xlabel('Category', fontsize=12)
    plt.ylabel('Gross Margin per Unit (VND)', fontsize=12)
    plt.savefig("product_margin_by_category.png")
    print("Đã lưu biểu đồ: 'product_margin_by_category.png'")

else:
    print("\n[LỖI] Biến 'df_product' không tồn tại. Bỏ qua phân tích.")

"""* Freeze (chiếm 34.7% doanh thu và 37.3% lợi nhuận gộp) là động lực tăng trưởng chính và có tỷ suất lợi nhuận gộp trên doanh thu cao nhất và biên lợi nhuận gộp trên mỗi đơn vị cao nhất ($\approx 55.000$ VND).

* Coffee có tỷ suất lợi nhuận trên doanh thu và biên lợi nhuận gộp trên mỗi đơn vị thấp nhất ($\approx 32.000$ VND). Điều này đặt ra câu hỏi về chiến lược giá hoặc chi phí nguyên liệu cho Coffee.
"""

plt.figure(figsize=(18, 5)) # Kích thước cho 3 biểu đồ

# Biểu đồ 1: Doanh thu theo Cuối tuần
plt.subplot(1, 3, 1)
ax1 = sns.barplot(
    data=avg_rev_weekend,
    x="Is_Weekend_Macro",
    y="Daily_Revenue",
    palette="Set2"
)
plt.title("Average daily revenue (Weekdays and Weekends)")
plt.xlabel("")
plt.ylabel("Average revenue per day (VND)")
ax1.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, pos: f'{x/1e6:.0f}M')) # Format (Triệu)

# Biểu đồ 2: Lợi nhuận theo Cuối tuần
plt.subplot(1, 3, 2)
ax2 = sns.barplot(
    data=avg_profit_weekend,
    x="Is_Weekend_Macro",
    y="Daily_Profit",
    palette="Set3"
)
plt.title("Average daily profit (Weekdays and Weekends)")
plt.xlabel("")
plt.ylabel("Average profit per day (VND)")
ax2.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, pos: f'{x/1e6:.0f}M')) # Format (Triệu)

# Biểu đồ 3: Doanh thu theo Promotion
plt.subplot(1, 3, 3)
ax3 = sns.barplot(
    data=avg_rev_promo,
    x="Promotion_Campaign_Flag", # Corrected column name
    y="Daily_Revenue",
    palette="coolwarm"
)
plt.title("Average Revenue: Regular Days and Promo Days")
plt.xlabel("")
plt.ylabel("Average Revenue per day (VND)")
ax3.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, pos: f'{x/1e6:.0f}M')) # Format (Triệu)

plt.tight_layout()
plt.show()

# (Tùy chọn) Vẽ biểu đồ Lợi nhuận theo Promotion
plt.figure(figsize=(6, 5))
ax4 = sns.barplot(
    data=avg_profit_promo,
    x="Promotion_Campaign_Flag", # Corrected column name
    y="Daily_Profit",
    palette="coolwarm_r" # Palette đảo ngược
)
plt.title("Average Profit: Regular Day and Promo Day")
plt.xlabel("")
plt.ylabel("Average Profit per day (VND)")
ax4.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, pos: f'{x/1e6:.0f}M')) # Format (Triệu)
plt.show()

"""* Doanh thu và lợi nhuận đều tăng trưởng tích cực vào cuối tuần so với ngày thường, khẳng định sản phẩm/dịch vụ của doanh nghiệp phục vụ tốt cho nhu cầu giải trí và thư giãn.
* Chương trình khuyến mãi là yếu tố thúc đẩy hiệu quả nhất trong hệ thống. Ngày có Promo mang lại doanh thu và lợi nhuận trung bình mỗi ngày cao nhất, vượt qua cả hiệu suất cuối tuần.

####Theo thời vụ
"""

# =============================================================================
# 1.3. TIME & CONTEXT (WHEN DO SALES PEAK?)
# =============================================================================
print("\n--- 1.3. TIME & CONTEXT ---")

fig = plt.figure(figsize=(16, 12))
gs = fig.add_gridspec(2, 2)
fig.suptitle('1.3. Time Trends & Context', fontsize=16, fontweight='bold')

# Revenue by Hour (Line chart)
ax1 = fig.add_subplot(gs[0, 0])
hourly_rev = df_master.groupby('Hour')['Total_Paid'].sum()
sns.lineplot(x=hourly_rev.index, y=hourly_rev.values, marker='o', linewidth=2.5, color='red', ax=ax1)
ax1.set_title('Total Revenue by Hour (Identify Peak Hours)')
ax1.set_xlabel('Hour of Day')
ax1.set_ylabel('Total Revenue (VND)')
ax1.set_xticks(range(0, 24))
ax1.grid(True, linestyle='--', alpha=0.7)

# Revenue by DayOfWeek (Bar chart)
ax2 = fig.add_subplot(gs[0, 1])
dow_map = {0: 'Mon', 1: 'Tue', 2: 'Wed', 3: 'Thu', 4: 'Fri', 5: 'Sat', 6: 'Sun'}
dow_rev = df_master.groupby('DayOfWeek')['Total_Paid'].sum().reset_index()
dow_rev['DayName'] = dow_rev['DayOfWeek'].map(dow_map)
sns.barplot(data=dow_rev, x='DayName', y='Total_Paid', ax=ax2, palette='Blues_d')
ax2.set_title('Total Revenue by Day of Week')

# Heatmap DayOfWeek x Hour (Behavior Pattern)
ax3 = fig.add_subplot(gs[1, :])  # Span entire bottom row
heatmap_data = df_master.pivot_table(index='DayOfWeek', columns='Hour', values='Total_Paid', aggfunc='sum')
heatmap_data.index = heatmap_data.index.map(dow_map)
sns.heatmap(heatmap_data, cmap='YlOrRd', ax=ax3, cbar_kws={'label': 'Revenue'})
ax3.set_title('Revenue Heatmap: Day x Hour (Hotspots)')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()


# Seasonality (Revenue by Month)
plt.figure(figsize=(12, 5))
monthly_rev = df_master.groupby('Month')['Total_Paid'].sum().reset_index()
sns.barplot(data=monthly_rev, x='Month', y='Total_Paid', palette='Spectral')
plt.title('Seasonality: Total Revenue by Month')
plt.ylabel('Total Revenue')
plt.show()

"""* **Thời điểm cao điểm chính**: Doanh thu tập trung mạnh mẽ nhất vào buổi tối, đặc biệt từ 18:00 đến 22:00. Doanh thu tăng trưởng theo cấp số nhân trong khung giờ này.

* **Hiệu suất Cuối tuần**: Doanh thu cuối tuần (Thứ Bảy và Chủ Nhật) cao hơn đáng kể so với các ngày trong tuần. Đỉnh điểm doanh thu cao nhất đều tuần rơi vào các buổi tối Thứ Bảy và Chủ Nhật (sau 20:00).

* **Mùa cao điểm**: Doanh thu đạt đỉnh cao nhất vào các tháng mùa hè/mùa nóng là Tháng 5, Tháng 7, và Tháng 8. Tháng 7 có tổng doanh thu cao nhất trong năm.Doanh thu có sự tăng trưởng mạnh mẽ trở lại vào tháng 12. Đây là thời điểm cuối năm, có nhiều hoạt động tiệc tùng, lễ hội và nhu cầu tiêu dùng tăng cao.
"""

# 1.3. Phân tích Giao dịch (Transaction Data)
# ========================================================
print("\n--- [1.3] Bắt đầu Phân tích Giao dịch (Transaction Data) ---")

if df_trans is not None:

    # --- Feature Engineering (Bắt buộc) ---
    print("\n[1.3.0] Feature Engineering (Giao dịch)...")
    try:
        df_trans['Date_Time'] = pd.to_datetime(df_trans['Date_Time'])
        df_trans['Hour'] = df_trans['Date_Time'].dt.hour
        df_trans['DayOfWeek'] = df_trans['Date_Time'].dt.day_name()
        print("Đã tạo cột 'Hour' và 'DayOfWeek' từ 'Date_Time'.")
    except Exception as e:
        print(f"Lỗi khi chuyển đổi Date_Time: {e}")
    # Câu hỏi: Khách hàng thường mua bao nhiêu món hàng trong 1 lần? (Top 5)
    plt.figure(figsize=(10, 6))
    top_5_quantity = df_trans['Quantity'].value_counts().nlargest(5).index
    sns.countplot(data=df_trans, x='Quantity', order=top_5_quantity)
    plt.title('Phân bổ Số lượng (Quantity) hàng/lần giao dịch (Top 5)')
    plt.xlabel('Số lượng (Quantity)')
    plt.ylabel('Tần suất')
    plt.savefig("trans_quantity_distribution.png")
    print("Đã lưu biểu đồ: 'trans_quantity_distribution.png'")

    # Câu hỏi: Tần suất giảm giá có nhiều không?
    discount_pct = (df_trans['Discount_Amount'] > 0).mean() * 100
    print(f"\nPhân tích Giảm giá (Discount_Amount):")
    print(f"  - Tỷ lệ giao dịch có giảm giá: {discount_pct:.2f}%")

    # Phân phối của các khoản giảm giá (chỉ xem các giá trị > 0)
    df_trans_with_discount = df_trans[df_trans['Discount_Amount'] > 0]
    plt.figure(figsize=(10, 6))
    sns.histplot(df_trans_with_discount['Discount_Amount'], kde=True, bins=30)
    plt.title('Phân phối của Discount_Amount (chỉ các giao dịch có giảm giá)')
    plt.xlabel('Số tiền giảm giá (VND)')
    plt.ylabel('Tần suất')
    plt.savefig("trans_hist_discount_amount.png")
    print("  - Đã lưu biểu đồ: 'trans_hist_discount_amount.png'")
    # Dùng Histogram
    # Giới hạn ở p99 để biểu đồ dễ nhìn hơn, vì có thể có outliers rất lớn
    p99 = df_trans['Total_Paid'].quantile(0.99)
    plt.figure(figsize=(10, 6))
    sns.histplot(df_trans[df_trans['Total_Paid'] < p99]['Total_Paid'], kde=True, bins=50)
    plt.title(f'Phân phối Tổng thanh toán (Total_Paid) (dưới {p99:,.0f} VND)')
    plt.xlabel('Tổng thanh toán (VND)')
    plt.ylabel('Tần suất')
    plt.savefig("trans_hist_total_paid.png")
    print("  - Đã lưu biểu đồ: 'trans_hist_total_paid.png'")

    # Dùng Box Plot để phát hiện outliers
    plt.figure(figsize=(10, 6))
    sns.boxplot(data=df_trans, y='Total_Paid')
    plt.title('Phân phối Total_Paid (Box Plot) - Hiển thị Outliers')
    plt.ylabel('Tổng thanh toán (VND)')
    plt.ylim(0, p99 * 1.5) # Giới hạn trục y để biểu đồ dễ nhìn hơn
    plt.savefig("trans_boxplot_total_paid.png")
    print("  - Đã lưu biểu đồ: 'trans_boxplot_total_paid.png'")

else:
    print("Lỗi: Không thể phân tích df_trans vì tải dữ liệu thất bại.")

print("\n--- Hoàn thành EDA 1.2 và 1.3 ---")

"""* Đại đa số giao dịch là mua 1 sản phẩm duy nhất (chiếm hơn 2/3 tổng giao dịch), cho thấy khách hàng thường mua cho bản thân hoặc mua lẻ.
* Giá trị giao dịch trung bình khá thấp (khoảng 70.000 VND). Sự tồn tại của nhiều outliers cho thấy có một số khách hàng/giao dịch giá trị cao đóng vai trò quan trọng, nhưng chủ yếu là các giao dịch nhỏ.
* Các chương trình giảm giá được sử dụng chủ yếu là các mức chiết khấu thấp, nhằm khuyến khích hành vi mua hàng mà không gây ảnh hưởng quá lớn đến biên lợi nhuận gộp.
"""

# 1.3. Transaction Analysis (Transaction Data)
# ========================================================
print("\n--- [1.3] Starting Transaction Analysis (Transaction Data) ---")

if df_trans is not None:

    # --- Feature Engineering (Required) ---
    print("\n[1.3.0] Feature Engineering (Transaction Data)...")
    try:
        df_trans['Date_Time'] = pd.to_datetime(df_trans['Date_Time'])
        df_trans['Hour'] = df_trans['Date_Time'].dt.hour
        df_trans['DayOfWeek'] = df_trans['Date_Time'].dt.day_name()
        print("Created columns 'Hour' and 'DayOfWeek' from 'Date_Time'.")
    except Exception as e:
        print(f"Error converting Date_Time: {e}")

    # Question: How many items do customers typically buy per transaction? (Top 5)
    plt.figure(figsize=(10, 6))
    top_5_quantity = df_trans['Quantity'].value_counts().nlargest(5).index
    sns.countplot(data=df_trans, x='Quantity', order=top_5_quantity)
    plt.title('Distribution of Quantity per Transaction (Top 5)')
    plt.xlabel('Quantity')
    plt.ylabel('Frequency')
    plt.savefig("trans_quantity_distribution.png")
    print("Saved figure: 'trans_quantity_distribution.png'")

    # Question: How frequent are discounts?
    discount_pct = (df_trans['Discount_Amount'] > 0).mean() * 100
    print(f"\nDiscount Analysis (Discount_Amount):")
    print(f"  - Percentage of transactions with discount: {discount_pct:.2f}%")

    # Distribution of discount amounts (only positive values)
    df_trans_with_discount = df_trans[df_trans['Discount_Amount'] > 0]
    plt.figure(figsize=(10, 6))
    sns.histplot(df_trans_with_discount['Discount_Amount'], kde=True, bins=30)
    plt.title('Distribution of Discount_Amount (only discounted transactions)')
    plt.xlabel('Discount Amount (VND)')
    plt.ylabel('Frequency')
    plt.savefig("trans_hist_discount_amount.png")
    print("  - Saved figure: 'trans_hist_discount_amount.png'")

    # Histogram for Total_Paid (limit at p99 for readability)
    p99 = df_trans['Total_Paid'].quantile(0.99)
    plt.figure(figsize=(10, 6))
    sns.histplot(df_trans[df_trans['Total_Paid'] < p99]['Total_Paid'], kde=True, bins=50)
    plt.title(f'Distribution of Total_Paid (below {p99:,.0f} VND)')
    plt.xlabel('Total Paid (VND)')
    plt.ylabel('Frequency')
    plt.savefig("trans_hist_total_paid.png")
    print("  - Saved figure: 'trans_hist_total_paid.png'")

    # Box Plot to detect outliers
    plt.figure(figsize=(10, 6))
    sns.boxplot(data=df_trans, y='Total_Paid')
    plt.title('Distribution of Total_Paid (Box Plot) - Outlier Detection')
    plt.ylabel('Total Paid (VND)')
    plt.ylim(0, p99 * 1.5)
    plt.savefig("trans_boxplot_total_paid.png")
    print("  - Saved figure: 'trans_boxplot_total_paid.png'")

else:
    print("Error: Cannot analyze df_trans because data loading failed.")

print("\n--- Completed EDA 1.2 and 1.3 ---")

"""#Đa biến

###Phân tích Chân dung Khách hàng & Giá trị (Customer Segmentation & Value)
"""

sns.set(style="whitegrid")

df = df_master_reduced.copy()

# ===========================================================
# 2.1.1. Chuẩn bị dữ liệu khách hàng (Customer-Level Aggregation)
# ===========================================================

# Tổng chi tiêu mỗi khách
customer_value = (
    df.groupby("Customer_ID")
      .agg(
          Total_Spend=("Total_Paid", "sum"),
          Total_Orders=("Transaction_ID", "nunique"),
          Total_Quantity=("Quantity", "sum"),
          Income_Level=("Income_Level", "first"),
          Membership_Tier=("Membership_Tier", "first"),
          Age=("Age", "first"),
          Age_Group=("Age_Group", "first"),
          Occupation=("Occupation", "first")
      )
      .reset_index()
)

# Frequency = số lần mua
customer_value["Frequency"] = customer_value["Total_Orders"]

print("\n=== Customer Value Table (Preview) ===")
print(customer_value.head())

# ===========================================================
# 2.1.2. Tương quan Income Level vs. Total Spend
# ===========================================================

plt.figure(figsize=(10, 5))
sns.boxplot(
    data=customer_value,
    x="Income_Level",
    y="Total_Spend",
    palette="Pastel1"
)
plt.title("Income Level vs Total Spend")
plt.xlabel("Income Level")
plt.ylabel("Tổng chi tiêu (VND)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ===========================================================
# 2.1.3. Membership Tier vs Total Spend / Frequency
# ===========================================================

# Boxplot: Total Spend theo Membership Tier
plt.figure(figsize=(10, 5))
sns.boxplot(
    data=customer_value,
    x="Membership_Tier",
    y="Total_Spend",
    palette="Pastel1"
)
plt.title("Membership Tier vs Total Spend")
plt.xlabel("Membership Tier")
plt.ylabel("Tổng chi tiêu (VND)")
plt.tight_layout()
plt.show()

# ===========================================================
# 2.1.4. Age vs Total Spend (liên tục + theo Age Group)
# ===========================================================

# Boxplot: Age Group vs Total Spend
plt.figure(figsize=(10, 5))
sns.boxplot(
    data=customer_value,
    x="Age_Group",
    y="Total_Spend",
    palette="Pastel1"
)
plt.title("Age Group vs Total Spend")
plt.xlabel("Age Group")
plt.ylabel("Total Spend (VND)")
plt.tight_layout()
plt.show()

# ===========================================================
# 2.1.5. Heatmap Correlation (numeric)
# ===========================================================

numeric_cols = ["Total_Spend", "Frequency", "Total_Quantity", "Age"]
corr = customer_value[numeric_cols].corr()

plt.figure(figsize=(7, 5))
sns.heatmap(corr, annot=True, cmap="Purples", linewidths=0.5)
plt.title("Correlation Heatmap – Customer Value Metrics")
plt.show()

# ===========================================================
# 2.1.6. Income Level vs Frequency (khách thu nhập thấp có quay lại nhiều?)
# ===========================================================

plt.figure(figsize=(10, 5))
sns.boxplot(
    data=customer_value,
    x="Income_Level",
    y="Frequency",
    palette="Pastel1"
)
plt.title("Income Level vs Frequency (Return Rate)")
plt.xlabel("Income Level")
plt.ylabel("Số lần mua (Frequency)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ===========================================================
# 2.1.7. Occupation vs Total Spend (Student vs Office Worker…)
# ===========================================================

plt.figure(figsize=(10, 5))
sns.boxplot(
    data=customer_value,
    x="Occupation",
    y="Total_Spend",
    palette="Pastel1"
)
plt.title("Occupation vs Total Spend")
plt.xlabel("Occupation")
plt.ylabel("Tổng chi tiêu (VND)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

sns.set(style="whitegrid")

df = df_master_reduced.copy()

# ===========================================================
# 2.1.1. Prepare Customer-Level Aggregation
# ===========================================================

# Total spending per customer
customer_value = (
    df.groupby("Customer_ID")
      .agg(
          Total_Spend=("Total_Paid", "sum"),
          Total_Orders=("Transaction_ID", "nunique"),
          Total_Quantity=("Quantity", "sum"),
          Income_Level=("Income_Level", "first"),
          Membership_Tier=("Membership_Tier", "first"),
          Age=("Age", "first"),
          Age_Group=("Age_Group", "first"),
          Occupation=("Occupation", "first")
      )
      .reset_index()
)

# Frequency = number of purchases
customer_value["Frequency"] = customer_value["Total_Orders"]

print("\n=== Customer Value Table (Preview) ===")
print(customer_value.head())

# ===========================================================
# 2.1.2. Income Level vs Total Spend
# ===========================================================

plt.figure(figsize=(10, 5))
sns.boxplot(
    data=customer_value,
    x="Income_Level",
    y="Total_Spend",
    palette="Pastel1"
)
plt.title("Income Level vs Total Spend")
plt.xlabel("Income Level")
plt.ylabel("Total Spend (VND)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ===========================================================
# 2.1.3. Membership Tier vs Total Spend / Frequency
# ===========================================================

# Boxplot: Total Spend by Membership Tier
plt.figure(figsize=(10, 5))
sns.boxplot(
    data=customer_value,
    x="Membership_Tier",
    y="Total_Spend",
    palette="Pastel1"
)
plt.title("Membership Tier vs Total Spend")
plt.xlabel("Membership Tier")
plt.ylabel("Total Spend (VND)")
plt.tight_layout()
plt.show()

# ===========================================================
# 2.1.4. Age vs Total Spend (continuous + Age Group)
# ===========================================================

plt.figure(figsize=(10, 5))
sns.boxplot(
    data=customer_value,
    x="Age_Group",
    y="Total_Spend",
    palette="Pastel1"
)
plt.title("Age Group vs Total Spend")
plt.xlabel("Age Group")
plt.ylabel("Total Spend (VND)")
plt.tight_layout()
plt.show()

# ===========================================================
# 2.1.5. Correlation Heatmap (numeric)
# ===========================================================

numeric_cols = ["Total_Spend", "Frequency", "Total_Quantity", "Age"]
corr = customer_value[numeric_cols].corr()

plt.figure(figsize=(7, 5))
sns.heatmap(corr, annot=True, cmap="Purples", linewidths=0.5)
plt.title("Correlation Heatmap – Customer Value Metrics")
plt.show()

# ===========================================================
# 2.1.6. Income Level vs Frequency (Do lower-income customers return more?)
# ===========================================================

plt.figure(figsize=(10, 5))
sns.boxplot(
    data=customer_value,
    x="Income_Level",
    y="Frequency",
    palette="Pastel1"
)
plt.title("Income Level vs Frequency (Return Rate)")
plt.xlabel("Income Level")
plt.ylabel("Purchase Frequency")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ===========================================================
# 2.1.7. Occupation vs Total Spend (Student vs Office Worker…)
# ===========================================================

plt.figure(figsize=(10, 5))
sns.boxplot(
    data=customer_value,
    x="Occupation",
    y="Total_Spend",
    palette="Pastel1"
)
plt.title("Occupation vs Total Spend")
plt.xlabel("Occupation")
plt.ylabel("Total Spend (VND)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""1. Insight: Hai "Trụ cột" Khách hàng (Từ Biểu đồ 1 & 2)
- Nhân viên Văn phòng là tệp khách hàng cốt lõi, đóng góp gần một nửa (45.3%) doanh thu, Sinh viên (Student) là trụ cột thứ hai với 23.4%.

2. Insight: Sự Lãng phí của Giảm giá "Cào bằng"
- Chiến lược giảm giá hiện tại đang lãng phí nghiêm trọng. Highlands "phí tiền" giảm giá cho các nhóm khách hàng cao cấp (Director, >50M) – những người gần như không nhạy cảm về giá – với tỷ lệ tương đương nhóm nhạy cảm giá.

3. Insight: Mâu thuẫn "Khẩu vị vs. Lợi nhuận"
- Nhân viên Văn phòng (nhóm ít nhạy cảm giá, thu nhập cao) lại là nhóm tiêu thụ Coffee (sản phẩm lời thấp) nhiều nhất.
- Sinh viên (Student) (nhóm rất nhạy cảm giá) lại tiêu thụ Tea (sản phẩm "Ngôi sao", lời cao) nhiều nhất.
=> Kết luận 3: Highlands đang bán sản phẩm lời ít nhất (Coffee) cho nhóm khách hàng sẵn sàng trả giá cao nhất (Office Worker) và sản phẩm lời nhiều (Tea) cho nhóm khách hàng nhạy cảm giá nhất (Student).

###

###Tính chỉ số hiệu suất & lợi nhuận theo sản phẩm
"""

# Set plot style
sns.set(style="whitegrid", palette="pastel")

# ======================================================
# 0. TẢI DỮ LIỆU
# ======================================================
try:
    df_trans = pd.read_csv("transaction_data.csv")
    df_product = pd.read_csv("product_master.csv")
    print("Tải dữ liệu transaction_data.csv và product_master.csv thành công.")
except FileNotFoundError as e:
    print(f"Lỗi: Không tìm thấy file. {e}")
    df_trans = None
    df_product = None
except Exception as e:
    print(f"Lỗi không xác định khi tải dữ liệu: {e}")
    df_trans = None
    df_product = None

# ======================================================
# 2.2. PHÂN TÍCH HIỆU SUẤT SẢN PHẨM & LỢI NHUẬN
# ======================================================

if df_trans is not None and df_product is not None:

    print("\n--- [2.2.1] Chuẩn bị dữ liệu hiệu suất sản phẩm ---")

    # 1. Tính Lợi nhuận gộp (Gross Margin) trên df_product
    df_product['Gross_Margin_Per_Unit'] = df_product['Unit_Price_List'] - df_product['COGS']

    # 2. Tính toán tổng hợp từ df_trans
    # Nhóm theo từng Product_ID (SKU)
    product_sales_agg = df_trans.groupby('Product_ID').agg(
        Total_Quantity_Sold=('Quantity', 'sum'),
        Total_Revenue=('Total_Paid', 'sum')
    ).reset_index()

    # 3. Kết hợp (Merge) dữ liệu sales_agg với product_master
    df_perf = pd.merge(
        product_sales_agg,
        df_product,
        on='Product_ID',
        how='left'
    )

    # Tạo cột tên + size để dễ đọc biểu đồ
    df_perf['Product_Name_Size'] = df_perf['Product_Name'] + ' (' + df_perf['Size'] + ')'

    print("Dữ liệu hiệu suất sản phẩm (df_perf) đã sẵn sàng.")
    print(df_perf[['Product_Name_Size', 'Total_Quantity_Sold', 'Total_Revenue', 'Gross_Margin_Per_Unit']].head())

    # --- Phân tích 1: Top Bán chạy (Theo Doanh thu & Số lượng) ---
    print("\n--- [2.2.2] Phân tích Top Bán Chạy ---")

    top_n = 10 # Lấy Top 10

    # Top 10 theo SỐ LƯỢNG
    top_10_qty = df_perf.sort_values(by='Total_Quantity_Sold', ascending=False).head(top_n)

    plt.figure(figsize=(12, 7))
    ax = sns.barplot(data=top_10_qty, x='Total_Quantity_Sold', y='Product_Name_Size', hue='Category', dodge=False)
    plt.title(f'Top {top_n} Best-Selling Products by QUANTITY (Popularity)')
    plt.xlabel('Total Quantity Sold')
    plt.ylabel('Products')
    plt.legend(title='Category')
    plt.tight_layout()
    plt.savefig("product_top10_quantity.png")
    print("Đã lưu biểu đồ: 'product_top10_quantity.png'")

    # Top 10 theo DOANH THU
    top_10_rev = df_perf.sort_values(by='Total_Revenue', ascending=False).head(top_n)

    plt.figure(figsize=(12, 7))
    ax = sns.barplot(data=top_10_rev, x='Total_Revenue', y='Product_Name_Size', hue='Category', dodge=False)
    plt.title(f'Top {top_n} Best-Selling Products by REVENUE')
    plt.xlabel('Total Revenue (VND)')
    plt.ylabel('Products')
    # Format x-axis cho dễ đọc (hiển thị triệu)
    ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, pos: f'{x/1e6:.1f}M'))
    plt.legend(title='Category')
    plt.tight_layout()
    plt.savefig("product_top10_revenue.png")
    print("Đã lưu biểu đồ: 'product_top10_revenue.png'")

    # --- Phân tích 3: Ma trận Lợi nhuận (Popularity vs Profitability) ---
    print("\n--- [2.2.4] Phân tích Ma trận Lợi nhuận ---")

    # Trục X: Tổng Quantity đã bán (Popularity)
    # Trục Y: Gross_Margin_Per_Unit (Profitability)

    # Lấy đường trung vị (median) để chia 4 góc
    qty_median = df_perf['Total_Quantity_Sold'].median()
    margin_median = df_perf['Gross_Margin_Per_Unit'].median()

    plt.figure(figsize=(12, 8))
    sns.scatterplot(
        data=df_perf,
        x='Total_Quantity_Sold',
        y='Gross_Margin_Per_Unit',
        hue='Category',
        style='Size',
        s=150,
        alpha=0.8
    )

    # Vẽ 2 đường trung vị
    plt.axvline(qty_median, color='grey', linestyle='--', linewidth=1)
    plt.axhline(margin_median, color='grey', linestyle='--', linewidth=1)

    plt.title('Profit Matrix: Popularity (Units Sold) vs Profitability (Margin per Unit)', fontsize=16)
    plt.xlabel('Total Quantity Sold (Popularity Level)', fontsize=12)
    plt.ylabel('Gross Margin Per Unit (Profitability)', fontsize=12)

    # Thêm text chú thích cho 4 góc
    plt.text(qty_median * 1.05, margin_median * 1.05,
             'Stars\n(High Sales, High Margin)', fontsize=10, color='blue', alpha=0.7)

    plt.text(qty_median * 1.05, margin_median * 0.95,
             'Volume Drivers\n(High Sales, Low Margin)', fontsize=10, color='red', alpha=0.7, va='top')

    plt.text(qty_median * 0.95, margin_median * 1.05,
             'Niche\n(Low Sales, High Margin)', fontsize=10, color='green', alpha=0.7, ha='right')

    plt.text(qty_median * 0.95, margin_median * 0.95,
             'Dogs\n(Low Sales, Low Margin)', fontsize=10, color='grey', alpha=0.7, ha='right', va='top')

    plt.legend(title='Legend', loc='upper left', bbox_to_anchor=(1, 1))
    plt.tight_layout(rect=[0, 0, 0.85, 1])
    plt.savefig("product_profit_matrix.png")
    print("Đã lưu biểu đồ: 'product_profit_matrix.png'")

    print("\n--- Hoàn thành Phân tích 2.2 ---")

else:
    print("Không thể thực hiện phân tích do lỗi tải dữ liệu.")

"""1. Insight:
Toàn bộ sản phẩm được chia thành 3 cụm (cluster):
* Cụm 1: Coffee (Bò sữa - Góc dưới bên phải): bán chạy nhưng lời thấp. Đây chính là nhóm sản phẩm "vấn đề" rủi ro khi chi phí đầu vào tăng.
* Cụm 2: Tea (Ngôi sao - Góc trên bên phải):  vừa bán chạy, vừa lời cao. Đây là nhóm sản phẩm "hero" của công ty.
* Cụm 3: Freeze (Tiềm năng/Niche - Góc trên bên trái): bán chưa chạy nhưng có lợi nhuận gộp CAO NHẤT.

2. Insight: "Trà Sen Vàng" là Siêu-Ngôi-sao (Super-Star)

* "Trà Sen Vàng" (Size S, M, L) chiếm cả 3 vị trí đầu tiên. Đây không chỉ là một sản phẩm "Ngôi sao" (như Cụm 2), mà là một "Siêu-Ngôi-sao" tuyệt đối về mặt doanh số.
* Toàn bộ Top 10 chỉ bao gồm Coffee và Tea. Không có sản phẩm Freeze nào đủ bán chạy để lọt vào Top 10 về Số lượng.
Kết nối: Điều này củng cố Insight số 3. Sản phẩm Tea (mà Student rất thích) đang là sản phẩm chủ lực tuyệt đối về số lượng.


3. Insight: "Freeze" là Cỗ máy kiếm tiền "ẩn"
* Dù không lọt Top 10 về Số lượng, nhưng "Freeze Sô-cô-la (L)" và "Freeze Trà Xanh (L)" lại nhảy vọt lên vị trí #2 và #4 về Doanh thu vì Freeze có giá bán (Unit Price) rất cao
* Nhóm Freeze (lời cao nhất) đang được mua bởi nhóm khách hàng cao cấp (Director/Business Owner) và họ không nhạy cảm giá. Dù Freeze bán chậm, nó vẫn là một cỗ máy kiếm tiền quan trọng. Đây là cơ hội lớn để upsell (bán thêm) hoặc marketing cho nhóm này

###Price Sensitivity Analysis
"""

sns.set(style="whitegrid", palette="pastel")

# Kiểm tra dữ liệu
if df_trans is not None and df_product is not None and df_customer is not None:
    print("\n--- [2.3.2] Phân tích Giảm giá (Dữ liệu Giao dịch) ---")

    df_trans['Used_Discount'] = df_trans['Discount_Amount'] > 0

    product_discount_rate = df_trans.groupby('Product_ID')['Used_Discount'].mean().reset_index()

    product_info = df_product[['Product_ID', 'Product_Name', 'Size']].drop_duplicates()
    product_info['Product_Name_Size'] = product_info['Product_Name'] + ' (' + product_info['Size'] + ')'

    merged_product_discount = pd.merge(product_discount_rate, product_info, on='Product_ID')

    top_10_discounted = merged_product_discount.sort_values('Used_Discount', ascending=False).head(10)

    plt.figure(figsize=(12, 7))
    sns.barplot(data=top_10_discounted, x='Used_Discount', y='Product_Name_Size')
    plt.title('Top 10 Products with Highest Discount Usage Rate')
    plt.xlabel('Discount Usage Rate')
    plt.ylabel('Product')
    plt.gca().xaxis.set_major_formatter(ticker.PercentFormatter(xmax=1.0))
    plt.tight_layout()
    plt.savefig("price_top10_discounted_products.png")
    print("Đã lưu biểu đồ: 'price_top10_discounted_products.png'")

    # Membership tier + income
    df_cust_trans = pd.merge(
        df_trans[['Customer_ID', 'Used_Discount']],
        df_customer[['Customer_ID', 'Membership_Tier', 'Income level']],
        on='Customer_ID',
        how='left'
    )

    tier_discount = df_cust_trans.groupby('Membership_Tier')['Used_Discount'].mean().reset_index().sort_values('Used_Discount', ascending=False)

    plt.figure(figsize=(10, 6))
    sns.barplot(data=tier_discount, x='Membership_Tier', y='Used_Discount')
    plt.title('Discount Usage Rate by Membership Tier')
    plt.xlabel('Membership Tier')
    plt.ylabel('Discount Usage Rate')
    plt.gca().yaxis.set_major_formatter(ticker.PercentFormatter(xmax=1.0))
    plt.tight_layout()
    plt.savefig("price_discount_by_tier.png")
    print("Đã lưu biểu đồ: 'price_discount_by_tier.png'")

    income_order = ['< 2M', '2-5M', '5-10M', '10-20M', '20-50M', '> 50M']
    income_discount = df_cust_trans.groupby('Income level')['Used_Discount'].mean().reindex(income_order).reset_index()

    plt.figure(figsize=(12, 6))
    sns.barplot(data=income_discount, x='Income level', y='Used_Discount')
    plt.title('Discount Usage Rate by Income Level')
    plt.xlabel('Income Level')
    plt.ylabel('Discount Usage Rate')
    plt.gca().yaxis.set_major_formatter(ticker.PercentFormatter(xmax=1.0))
    plt.tight_layout()
    plt.savefig("price_discount_by_income.png")
    print("Đã lưu biểu đồ: 'price_discount_by_income.png'")

    # --- [2.3.2b] PHÂN TÍCH THEO NGHỀ NGHIỆP (THÊM MỚI) ---
    print("\n--- [2.3.2b] Phân tích theo Nghề nghiệp (Discount Rate & Gross Margin) ---")

    # Tạo một dataframe tổng hợp để phân tích
    try:
        # Merge Trans + Customer
        df_merge_cust = pd.merge(
            df_trans[['Customer_ID', 'Product_ID', 'Quantity', 'Unit_Price_Listed', 'Discount_Amount', 'Total_Paid']],
            df_customer[['Customer_ID', 'Occupation']],
            on='Customer_ID',
            how='left'
        )

        # Merge Trans+Cust + Product
        df_full_analysis = pd.merge(
            df_merge_cust,
            df_product[['Product_ID', 'COGS']],
            on='Product_ID',
            how='left'
        )

        # Kiểm tra null sau khi merge (quan trọng nếu có Product_ID không khớp)
        df_full_analysis.dropna(subset=['Occupation', 'COGS'], inplace=True)

        # Tính toán các cột cần thiết
        df_full_analysis['Total_List_Price'] = df_full_analysis['Quantity'] * df_full_analysis['Unit_Price_Listed']
        df_full_analysis['Transaction_Margin'] = df_full_analysis['Total_Paid'] - (df_full_analysis['COGS'] * df_full_analysis['Quantity'])

        print("Đã tạo dataframe tổng hợp cho phân tích Nghề nghiệp.")

        # ----- BIỂU ĐỒ 1: TỶ LỆ GIẢM GIÁ THỰC TẾ (%) THEO NGHỀ NGHIỆP -----

        # 1. Group by Occupation, sum Discount_Amount and Total_List_Price
        df_discount_occ = df_full_analysis.groupby('Occupation').agg(
            Total_Discount=('Discount_Amount', 'sum'),
            Total_List_Value=('Total_List_Price', 'sum')
        ).reset_index()

        # 2. Calculate the effective Discount Rate (tránh chia cho 0)
        df_discount_occ['Discount_Rate_Percent'] = 0.0
        df_discount_occ.loc[df_discount_occ['Total_List_Value'] > 0, 'Discount_Rate_Percent'] = \
            (df_discount_occ['Total_Discount'] / df_discount_occ['Total_List_Value']) * 100

        # 3. Sort by Discount Rate
        df_discount_occ = df_discount_occ.sort_values('Discount_Rate_Percent', ascending=False)

        print("\nĐang vẽ 'price_discount_rate_by_occupation.png'...")
        plt.figure(figsize=(14, 7))
        ax1 = sns.barplot(data=df_discount_occ, x='Occupation', y='Discount_Rate_Percent')
        plt.title('Discount rate by occupation')
        plt.xlabel('Occupation')
        plt.ylabel('Discount rate (%)')
        ax1.yaxis.set_major_formatter(ticker.PercentFormatter(xmax=100.0)) # Vì số đã được nhân 100
        plt.xticks(rotation=45, ha='right')
        plt.tight_layout()
        plt.savefig("price_discount_rate_by_occupation.png")
        print("Đã lưu biểu đồ: 'price_discount_rate_by_occupation.png'")

        # ----- BIỂU ĐỒ 2: LỢI NHUẬN GỘP TRUNG BÌNH (VND) THEO NGHỀ NGHIỆP -----

        # 1. Group by Occupation, get mean of Transaction_Margin
        df_margin_occ = df_full_analysis.groupby('Occupation')['Transaction_Margin'].mean().reset_index()

        # 2. Sort by margin
        df_margin_occ = df_margin_occ.sort_values('Transaction_Margin', ascending=False)

        print("\nĐang vẽ 'price_avg_margin_by_occupation.png'...")
        plt.figure(figsize=(14, 7))
        ax2 = sns.barplot(data=df_margin_occ, x='Occupation', y='Transaction_Margin')
        plt.title('Margin Profit by Occupation')
        plt.xlabel('Occupation')
        plt.ylabel('Margin Profit (VND)')
        ax2.get_yaxis().set_major_formatter(ticker.FuncFormatter(lambda x, p: format(int(x), ','))) # Format số cho dễ đọc
        plt.xticks(rotation=45, ha='right')
        plt.tight_layout()
        plt.savefig("price_avg_margin_by_occupation.png")
        print("Đã lưu biểu đồ: 'price_avg_margin_by_occupation.png'")

    except Exception as e:
        print(f"Lỗi trong khi tạo biểu đồ Nghề nghiệp: {e}")


    # --- [2.3.3] Kết hợp Khách hàng & Sản phẩm ---
    print("\n--- [2.3.3] Kết hợp Khách hàng & Sản phẩm ---")

    # Occupation vs Category
    df_occ_cat_merge = pd.merge(df_trans[['Customer_ID', 'Product_ID', 'Quantity']],
                                df_customer[['Customer_ID', 'Occupation']], on='Customer_ID')
    df_occ_cat_prod = pd.merge(df_occ_cat_merge, df_product[['Product_ID', 'Category']], on='Product_ID')

    occ_cat_crosstab = pd.crosstab(
        df_occ_cat_prod['Occupation'],
        df_occ_cat_prod['Category'],
        values=df_occ_cat_prod['Quantity'],
        aggfunc='sum',
        normalize='index'
    )

    plt.figure(figsize=(12, 8))
    sns.heatmap(occ_cat_crosstab, annot=True, fmt='.1%', cmap="YlGnBu", linewidths=.5)
    plt.title('Category Consumption Share by Occupation')
    plt.xlabel('Product Category')
    plt.ylabel('Occupation')
    plt.tight_layout()
    plt.savefig("price_heatmap_occupation_vs_category.png")
    print("Đã lưu biểu đồ: 'price_heatmap_occupation_vs_category.png'")